// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct _test	// sizeof = 0x0
{
};
#pragma pack(pop)

static_assert(sizeof(_test) == 0x0, "Incorrect struct size: _test");