// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct C2dfx	// sizeof = 0x34
{
	RwV3D pos;
	BYTE type;
	BYTE field_D[3];
	BYTE field_10;
	BYTE field_11;
	BYTE field_12;
	BYTE field_13;
	BYTE field_14;
	BYTE field_15;
	BYTE field_16;
	BYTE field_17;
	BYTE field_18;
	BYTE field_19;
	BYTE field_1A;
	BYTE field_1B;
	BYTE field_1C;
	BYTE field_1D;
	BYTE field_1E;
	BYTE field_1F;
	BYTE field_20;
	BYTE field_21;
	BYTE field_22;
	BYTE field_23;
	BYTE field_24;
	BYTE field_25;
	BYTE field_26;
	BYTE field_27;
	BYTE field_28;
	BYTE field_29;
	BYTE field_2A;
	BYTE field_2B;
	BYTE field_2C;
	BYTE field_2D;
	BYTE field_2E;
	BYTE field_2F;
	DWORD field_30;
};
#pragma pack(pop)

static_assert(sizeof(C2dfx) == 0x34, "Incorrect struct size: C2dfx");