// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CAiTimer	// sizeof = 0xC
{
	DWORD m_nStartTime;
	DWORD m_nInterval;
	BYTE m_bStarted;
	BYTE field_9;
	WORD __padding;
};
#pragma pack(pop)

static_assert(sizeof(CAiTimer) == 0xC, "Incorrect struct size: CAiTimer");