// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CAnimBlendSequence	// sizeof = 0xC
{
	DWORD hash;
	WORD flags;
	WORD frameCount;
	DWORD frames;
};
#pragma pack(pop)

static_assert(sizeof(CAnimBlendSequence) == 0xC, "Incorrect struct size: CAnimBlendSequence");