// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CAudioFileVtbl	// sizeof = 0x20
{
	DWORD init;
	DWORD read;
	DWORD getTotlaTimeInMS;
	DWORD getCurrentTimeInMS;
	DWORD seek;
	DWORD getSamplingRate;
	DWORD destructor;
	DWORD getId;
};
#pragma pack(pop)

static_assert(sizeof(CAudioFileVtbl) == 0x20, "Incorrect struct size: CAudioFileVtbl");