// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAudioFile.h"


#pragma pack(push, 1)
struct CAudioFileWindowsMedia	// sizeof = 0x8
{
	CAudioFile __parent;
};
#pragma pack(pop)

static_assert(sizeof(CAudioFileWindowsMedia) == 0x8, "Incorrect struct size: CAudioFileWindowsMedia");