// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAudioManager.h"


#pragma pack(push, 1)
struct CAudio	// sizeof = 0x4BC
{
	BYTE field_0[672];
	CAudioManager audioManager;
};
#pragma pack(pop)

static_assert(sizeof(CAudio) == 0x4BC, "Incorrect struct size: CAudio");