// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAudioFile.h"


#pragma pack(push, 1)
struct CAudioFileWav	// sizeof = 0x3C
{
	CAudioFile __parent;
	BYTE initialized;
	BYTE __pad[3];
	DWORD stream_;
	BYTE headerBuf[44];
};
#pragma pack(pop)

static_assert(sizeof(CAudioFileWav) == 0x3C, "Incorrect struct size: CAudioFileWav");