// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CAudioStream	// sizeof = 0x28
{
	DWORD __vmt;
	DWORD handle;
	DWORD filename;
	BYTE opened;
	BYTE __pad[3];
	DWORD currentPosition;
	DWORD startPosition;
	DWORD length;
	DWORD id;
	BYTE encrypted;
	BYTE __pad2[3];
	DWORD refCount;
};
#pragma pack(pop)

static_assert(sizeof(CAudioStream) == 0x28, "Incorrect struct size: CAudioStream");