// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CAudioFile	// sizeof = 0x8
{
	DWORD __vmt__;
	DWORD stream;
};
#pragma pack(pop)

static_assert(sizeof(CAudioFile) == 0x8, "Incorrect struct size: CAudioFile");