// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CVehicle_VTBL.h"


#pragma pack(push, 1)
struct CAutomobile_VTBL	// sizeof = 0x11C
{
	CVehicle_VTBL v;
	DWORD field_108;
	DWORD ResetSuspension;
	DWORD field_110;
	DWORD field_114;
	DWORD field_118;
};
#pragma pack(pop)

static_assert(sizeof(CAutomobile_VTBL) == 0x11C, "Incorrect struct size: CAutomobile_VTBL");