// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CBaseModelInfo	// sizeof = 0x20
{
	DWORD vmt;
	DWORD m_dwKey;
	WORD m_wUsageCount;
	WORD m_wTxdIndex;
	BYTE field_C;
	BYTE m_nbCount2dfx;
	WORD m_w2dfxIndex;
	WORD m_wObjectInfoIndex;
	WORD m_wFlags;
	DWORD m_pColModel;
	DWORD m_fDrawDistance;
	DWORD m_pRwObject;
};
#pragma pack(pop)

static_assert(sizeof(CBaseModelInfo) == 0x20, "Incorrect struct size: CBaseModelInfo");