// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CVehicle_VTBL.h"


#pragma pack(push, 1)
struct CBike_VTBL	// sizeof = 0x10C
{
	CVehicle_VTBL v;
	DWORD field_108;
};
#pragma pack(pop)

static_assert(sizeof(CBike_VTBL) == 0x10C, "Incorrect struct size: CBike_VTBL");