// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CBird	// sizeof = 0x44
{
	RwV3D pos;
	RwV3D RelatedToVelocity;
	RwV3D Velocity;
	DWORD angle;
	DWORD dw0_0;
	DWORD RelatedToWing;
	DWORD Size;
	DWORD MaxBirdDistance;
	BYTE b1_1;
	BYTE field_39;
	BYTE field_3A;
	BYTE field_3B;
	BYTE field_3C;
	BYTE field_3D;
	BYTE field_3E;
	BYTE HasBirdHere;
	BYTE MustDoCurves;
	BYTE field_41;
	BYTE field_42;
	BYTE field_43;
};
#pragma pack(pop)

static_assert(sizeof(CBird) == 0x44, "Incorrect struct size: CBird");