// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CVehicle.h"


#pragma pack(push, 1)
struct CBoat	// sizeof = 0x5A0
{
	CVehicle __parent;
};
#pragma pack(pop)

static_assert(sizeof(CBoat) == 0x5A0, "Incorrect struct size: CBoat");