// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CCamera_obj2	// sizeof = 0x10
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
};
#pragma pack(pop)

static_assert(sizeof(CCamera_obj2) == 0x10, "Incorrect struct size: CCamera_obj2");