// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwSphere.h"
#include "RwBBox.h"


#pragma pack(push, 1)
struct CColModel	// sizeof = 0x30
{
	RwBBox bbox;
	RwSphere sphere;
	BYTE field_28;
	BYTE flags;
	BYTE field_2A;
	BYTE field_2B;
	DWORD m_pColData;
};
#pragma pack(pop)

static_assert(sizeof(CColModel) == 0x30, "Incorrect struct size: CColModel");