// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CCollisionFile	// sizeof = 0x2C
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	WORD field_20;
	WORD field_22;
	WORD field_24;
	WORD field_26;
	BYTE field_28;
	BYTE field_29;
	BYTE field_2A;
	BYTE field_2B;
};
#pragma pack(pop)

static_assert(sizeof(CCollisionFile) == 0x2C, "Incorrect struct size: CCollisionFile");