// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CComponentLinks	// sizeof = 0x7C
{
	WORD component1[30];
	WORD component2[30];
	DWORD componentCount;
};
#pragma pack(pop)

static_assert(sizeof(CComponentLinks) == 0x7C, "Incorrect struct size: CComponentLinks");