// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CCullZoneBase.h"


#pragma pack(push, 1)
struct CCullZone	// sizeof = 0x12
{
	CCullZoneBase __parent;
	WORD flags;
};
#pragma pack(pop)

static_assert(sizeof(CCullZone) == 0x12, "Incorrect struct size: CCullZone");