// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CCullZoneBase	// sizeof = 0x10
{
	WORD x;
	WORD y;
	WORD field_4;
	WORD Ywidth;
	WORD Xwidth;
	WORD field_A;
	WORD Zbottom;
	WORD Ztop;
};
#pragma pack(pop)

static_assert(sizeof(CCullZoneBase) == 0x10, "Incorrect struct size: CCullZoneBase");