// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CPedEventList.h"
#include "CPedEvent_DM_List.h"


#pragma pack(push, 1)
struct CDecisionMakerMgr	// sizeof = 0xF1C0
{
	DWORD field_0;
	CPedEvent_DM_List decisionMakers[20];
	CPedEventList pedEventList;
	CPedEvent_DM_List field_C1B4;
	CPedEvent_DM_List field_CB50;
	CPedEvent_DM_List field_D4EC;
	CPedEvent_DM_List field_DE88;
	CPedEvent_DM_List field_E824;
};
#pragma pack(pop)

static_assert(sizeof(CDecisionMakerMgr) == 0xF1C0, "Incorrect struct size: CDecisionMakerMgr");