// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <cstdint>

#pragma pack(push, 1)
struct CDirectoryEntry	// sizeof = 0x20
{
	uint32_t fileOffset;
	uint16_t sizePriority2;
	uint16_t sizePriority1;
	char filename[24];
};
#pragma pack(pop)

static_assert(sizeof(CDirectoryEntry) == 0x20, "Incorrect struct size: CDirectoryEntry");
