// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "Queue.h"
#include "CdStream.h"


#pragma pack(push, 1)
struct CdStreamInfo	// sizeof = 0x8C0
{
	Queue queue;
	CdStream* pStreams;
	DWORD thread_id;
	HANDLE semaphore;
	HANDLE thread;
	HANDLE streamHandles[32];
	DWORD streamCount;
	DWORD openStreamCount;
	CHAR  streamNames[2048];
	DWORD field_8A8;
	DWORD lastPosn;
	DWORD field_8B0;
	DWORD field_8B4;
	DWORD gtaint_id;
	DWORD gta3_id;
};
#pragma pack(pop)

static_assert(sizeof(CdStreamInfo) == 0x8C0, "Incorrect struct size: CdStreamInfo");
