// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CDummy	// sizeof = 0x38
{
	DWORD __vmt;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	WORD field_20;
	WORD field_22;
	DWORD field_24;
	DWORD field_28;
	WORD field_2C;
	BYTE field_2E;
	BYTE field_2F;
	DWORD field_30;
	BYTE field_34;
	BYTE field_35;
	BYTE field_36;
	BYTE field_37;
};
#pragma pack(pop)

static_assert(sizeof(CDummy) == 0x38, "Incorrect struct size: CDummy");