// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CEntity_VTBL	// sizeof = 0x58
{
	DWORD SCALAR_DELETING_DESTRUCTOR;
	DWORD Add_CRect;
	DWORD Add;
	DWORD Remove;
	DWORD SetIsStatic;
	DWORD SetModelIndex;
	DWORD SetModelIndexNoCreate;
	DWORD CreateRwObject;
	DWORD DeleteRwObject;
	DWORD GetBoundRect;
	DWORD ProcessControl;
	DWORD ProcessCollision;
	DWORD ProcessShift;
	DWORD TestCollision;
	DWORD Teleport;
	DWORD SpecialEntityPreCollisionStuff;
	DWORD SpecialEntityCalcCollisionSteps;
	DWORD PreRender;
	DWORD Render;
	DWORD SetupLighting;
	DWORD RemoveLighting;
	DWORD FlagToDestroyWhenNextProcessed;
};
#pragma pack(pop)

static_assert(sizeof(CEntity_VTBL) == 0x58, "Incorrect struct size: CEntity_VTBL");