// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CEntryData	// sizeof = 0x12
{
	BYTE action;
	BYTE description[8];
	BYTE field_9;
	WORD targetMenu;
	WORD field_C;
	WORD field_E;
	WORD field_10;
};
#pragma pack(pop)

static_assert(sizeof(CEntryData) == 0x12, "Incorrect struct size: CEntryData");