// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CEntityScanner	// sizeof = 0x50
{
	DWORD __vmt;
	DWORD field_4;
	DWORD m_dwCount;
	DWORD m_apEntities[16];
	DWORD field_4C;
};
#pragma pack(pop)

static_assert(sizeof(CEntityScanner) == 0x50, "Incorrect struct size: CEntityScanner");