// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CEntryInfoNode	// sizeof = 0x14
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
};
#pragma pack(pop)

static_assert(sizeof(CEntryInfoNode) == 0x14, "Incorrect struct size: CEntryInfoNode");