// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CPlaceable.h"


#pragma pack(push, 1)
struct CEntity	// sizeof = 0x38
{
	CPlaceable __parent;
	DWORD m_pRWObject;
	DWORD field_1C;
	WORD RandomSeed;
	WORD m_wModelIndex;
	DWORD m_reference;
	DWORD field_28;
	WORD field_2C;
	BYTE field_2E;
	BYTE m_nbInterior;
	DWORD field_30;
	BYTE field_34;
	BYTE field_35;
	BYTE type;
	BYTE field_37;
};
#pragma pack(pop)

static_assert(sizeof(CEntity) == 0x38, "Incorrect struct size: CEntity");