// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CEvent	// sizeof = 0x44
{
	DWORD __vmt__;
	DWORD field_4;
	BYTE field_8;
	BYTE field_9;
	BYTE field_A;
	BYTE field_B;
	BYTE field_C;
	BYTE field_D;
	WORD field_E;
	WORD field_10;
	WORD field_12;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	BYTE field_30;
	BYTE field_31;
	BYTE field_32;
	BYTE field_33;
	DWORD field_34;
	DWORD field_38;
	DWORD field_3C;
	BYTE field_40;
	BYTE field_41;
	BYTE field_42;
	BYTE field_43;
};
#pragma pack(pop)

static_assert(sizeof(CEvent) == 0x44, "Incorrect struct size: CEvent");