// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CExternalScriptInfo	// sizeof = 0x20
{
	DWORD data;
	BYTE status;
	BYTE field_5;
	WORD wScmIndex;
	BYTE name[20];
	DWORD size;
};
#pragma pack(pop)

static_assert(sizeof(CExternalScriptInfo) == 0x20, "Incorrect struct size: CExternalScriptInfo");