// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CExternalScriptInfo.h"


#pragma pack(push, 1)
struct CExternalScripts	// sizeof = 0xA48
{
	CExternalScriptInfo scripts[82];
	DWORD field_A40;
	WORD field_A44;
	WORD field_A46;
};
#pragma pack(pop)

static_assert(sizeof(CExternalScripts) == 0xA48, "Incorrect struct size: CExternalScripts");