// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CFire	// sizeof = 0x28
{
	BYTE bUsed;
	BYTE field_1;
	WORD wUniqueID;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD pEntity;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
};
#pragma pack(pop)

static_assert(sizeof(CFire) == 0x28, "Incorrect struct size: CFire");