// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CFlippedCheck	// sizeof = 0x8
{
	DWORD vehicle;
	DWORD field_4;
};
#pragma pack(pop)

static_assert(sizeof(CFlippedCheck) == 0x8, "Incorrect struct size: CFlippedCheck");