// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CGangWeapons	// sizeof = 0x10
{
	BYTE field_0;
	BYTE __pad[3];
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
};
#pragma pack(pop)

static_assert(sizeof(CGangWeapons) == 0x10, "Incorrect struct size: CGangWeapons");