// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "CMatrix.h"


#pragma pack(push, 1)
struct CGrass	// sizeof = 0x70
{
	CMatrix field_0;
	DWORD field_48;
	DWORD field_4C;
	DWORD field_50;
	RwV3D field_54;
	DWORD CreatedTime;
	DWORD field_64;
	DWORD field_68;
	BYTE field_6C;
	BYTE ExistFlag;
	WORD field_6E;
};
#pragma pack(pop)

static_assert(sizeof(CGrass) == 0x70, "Incorrect struct size: CGrass");