// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CHandlingFlying	// sizeof = 0x58
{
	DWORD index;
	DWORD thrust;
	DWORD thrustFallOff;
	DWORD yaw;
	DWORD yawStab;
	DWORD sideSlip;
	DWORD roll;
	DWORD rollStab;
	DWORD pitch;
	DWORD pitchStab;
	DWORD formLift;
	DWORD attackLift;
	DWORD gearUpR;
	DWORD gearDownL;
	DWORD windMult;
	DWORD moveRes;
	RwV3D turnRes;
	RwV3D speedRes;
};
#pragma pack(pop)

static_assert(sizeof(CHandlingFlying) == 0x58, "Incorrect struct size: CHandlingFlying");