// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "CTransmissionData.h"


#pragma pack(push, 1)
struct CHandlingVehicle	// sizeof = 0xE0
{
	DWORD index;
	DWORD fMass;
	DWORD field_8;
	DWORD fTurnMass;
	DWORD fDragMult;
	RwV3D centreOfMass;
	BYTE nPercentSubmerged;
	BYTE field_21;
	BYTE field_22;
	BYTE field_23;
	DWORD field_24;
	DWORD fTractionMultiplier;
	CTransmissionData transmissionData;
	DWORD fBrakeDeceleration;
	DWORD fBrakeBias;
	BYTE bABS;
	BYTE field_9D;
	BYTE field_9E;
	BYTE field_9F;
	DWORD fSteeringLock;
	DWORD fTractionLoss;
	DWORD fTractionBias;
	DWORD fSuspensionForceLevel;
	DWORD fSuspensionDampingLevel;
	DWORD fSuspensionHighSpdComDamp;
	DWORD fSuspensionUpperLimit;
	DWORD fSuspensionLowerLimit;
	DWORD fSuspensionBiasBetweenFrontAndRear;
	DWORD fSuspensionAntiDiveMultiplier;
	DWORD fCollisionDamageMultiplier;
	DWORD modelFlags;
	DWORD handlingFlags;
	DWORD fSeatOffsetDistance;
	DWORD nMonetaryValue;
	BYTE frontLight;
	BYTE rearLight;
	BYTE animGroup;
	BYTE field_DF;
};
#pragma pack(pop)

static_assert(sizeof(CHandlingVehicle) == 0xE0, "Incorrect struct size: CHandlingVehicle");