// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CHandlingBoat.h"
#include "CHandlingFlying.h"
#include "CHandlingVehicle.h"
#include "CHandlingBike.h"


#pragma pack(push, 1)
struct CHandlingData	// sizeof = 0xC624
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	CHandlingVehicle vehicleHandling[210];
	CHandlingBike bikeHandling[13];
	CHandlingFlying flyingHandling[24];
	CHandlingBoat boatHandling[12];
};
#pragma pack(pop)

static_assert(sizeof(CHandlingData) == 0xC624, "Incorrect struct size: CHandlingData");