// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CHeliLight	// sizeof = 0x34
{
	RwV3D startPoint;
	RwV3D targetPoint;
	DWORD targetRadius;
	DWORD shadowIntensity;
	DWORD coronaIndex;
	BYTE unkFlag;
	BYTE enableShadow;
	WORD __pad;
	RwV3D unkData;
};
#pragma pack(pop)

static_assert(sizeof(CHeliLight) == 0x34, "Incorrect struct size: CHeliLight");