// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CIfpAnimations	// sizeof = 0x18
{
	DWORD hash;
	DWORD sequences;
	WORD seqCount;
	BYTE field_A;
	BYTE field_B;
	DWORD ifpFileIndex;
	DWORD field_10;
	DWORD field_14;
};
#pragma pack(pop)

static_assert(sizeof(CIfpAnimations) == 0x18, "Incorrect struct size: CIfpAnimations");