// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CImgDescriptor	// sizeof = 0x30
{
	BYTE name[40];
	BYTE isNotPlayerImg;
	BYTE __align[3];
	DWORD streamHandle;
};
#pragma pack(pop)

static_assert(sizeof(CImgDescriptor) == 0x30, "Incorrect struct size: CImgDescriptor");