// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "pair.h"


#pragma pack(push, 1)
struct CInputEvents__Event	// sizeof = 0x20
{
	pair data[4];
};
#pragma pack(pop)

static_assert(sizeof(CInputEvents__Event) == 0x20, "Incorrect struct size: CInputEvents__Event");