// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CInputEvents__EventName.h"
#include "CInputEvents__Event.h"
#include "DIJOYSTATE2.h"


#pragma pack(push, 1)
struct CInputEvents	// sizeof = 0x12E4
{
	BYTE field_0;
	BYTE field_1;
	BYTE field_2;
	BYTE field_3;
	DIJOYSTATE2 prevPadState;
	DIJOYSTATE2 currPadState;
	CInputEvents__EventName eventNames[59];
	BYTE field_B5C[17];
	BYTE __pad2[3];
	CInputEvents__Event events[59];
	BYTE field_12D0[16];
	BYTE field_12E0;
	BYTE __pad[3];
};
#pragma pack(pop)

static_assert(sizeof(CInputEvents) == 0x12E4, "Incorrect struct size: CInputEvents");