// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CInputEvents__EventName	// sizeof = 0x28
{
	BYTE name[40];
};
#pragma pack(pop)

static_assert(sizeof(CInputEvents__EventName) == 0x28, "Incorrect struct size: CInputEvents__EventName");