// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CIplFile	// sizeof = 0x34
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	BYTE name[16];
	WORD field_20;
	WORD field_22;
	WORD field_24;
	WORD field_26;
	WORD field_28;
	WORD iplId;
	BYTE field_2C;
	BYTE field_2D;
	BYTE field_2E;
	BYTE field_2F;
	BYTE field_30;
	BYTE field_31;
	BYTE field_32;
	BYTE field_33;
};
#pragma pack(pop)

static_assert(sizeof(CIplFile) == 0x34, "Incorrect struct size: CIplFile");