// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CKeyState	// sizeof = 0x270
{
	WORD FKeys[12];
	WORD standardKeys[256];
	WORD esc;
	WORD insert;
	WORD del;
	WORD home;
	WORD end;
	WORD pgup;
	WORD pgdn;
	WORD up;
	WORD down;
	WORD left;
	WORD right;
	WORD scroll;
	WORD pause;
	WORD numlock;
	WORD div;
	WORD mul;
	WORD sub;
	WORD add;
	WORD enter;
	WORD decimal;
	WORD num1;
	WORD num2;
	WORD num3;
	WORD num4;
	WORD num5;
	WORD num6;
	WORD num7;
	WORD num8;
	WORD num9;
	WORD num0;
	WORD back;
	WORD tab;
	WORD capslock;
	WORD extenter;
	WORD lshift;
	WORD rshift;
	WORD shift;
	WORD lctrl;
	WORD rctrl;
	WORD lmenu;
	WORD rmenu;
	WORD lwin;
	WORD rwin;
	WORD apps;
};
#pragma pack(pop)

static_assert(sizeof(CKeyState) == 0x270, "Incorrect struct size: CKeyState");