// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CLuminousPolygon	// sizeof = 0x38
{
	RwV3D pos;
	RwV3D right;
	RwV3D top;
	RwV3D at;
	DWORD distanceToCamera;
	BYTE colour;
	BYTE field_35;
	BYTE field_36;
	BYTE field_37;
};
#pragma pack(pop)

static_assert(sizeof(CLuminousPolygon) == 0x38, "Incorrect struct size: CLuminousPolygon");