// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CMatrix_Padded	// sizeof = 0x40
{
	RwV3D vRight;
	DWORD field_C;
	RwV3D vFront;
	DWORD field_1C;
	RwV3D vUp;
	DWORD field_2C;
	RwV3D vPos;
	DWORD field_3C;
};
#pragma pack(pop)

static_assert(sizeof(CMatrix_Padded) == 0x40, "Incorrect struct size: CMatrix_Padded");