// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CMaterialRestoreData	// sizeof = 0x8
{
	DWORD pMaterialField;
	DWORD OldData;
};
#pragma pack(pop)

static_assert(sizeof(CMaterialRestoreData) == 0x8, "Incorrect struct size: CMaterialRestoreData");