// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwMatrix.h"


#pragma pack(push, 1)
struct CMatrix	// sizeof = 0x48
{
	RwMatrix matrix;
	DWORD matrixPtr;
	DWORD haveRwMatrix;
};
#pragma pack(pop)

static_assert(sizeof(CMatrix) == 0x48, "Incorrect struct size: CMatrix");