// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CMenuStatDisplay	// sizeof = 0x6
{
	WORD StatID;
	BYTE Type;
	BYTE AlwaysDisplay;
	BYTE IsNonBasicStat;
	BYTE IsNamed;
};
#pragma pack(pop)

static_assert(sizeof(CMenuStatDisplay) == 0x6, "Incorrect struct size: CMenuStatDisplay");