// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CMissionCleanup	// sizeof = 0x8
{
	BYTE type;
	BYTE __pad[3];
	DWORD handle;
};
#pragma pack(pop)

static_assert(sizeof(CMissionCleanup) == 0x8, "Incorrect struct size: CMissionCleanup");