// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CBaseModelInfo.h"


#pragma pack(push, 1)
struct CModelObjs2c	// sizeof = 0x24
{
	CBaseModelInfo __parent;
	DWORD atomic2;
};
#pragma pack(pop)

static_assert(sizeof(CModelObjs2c) == 0x24, "Incorrect struct size: CModelObjs2c");