// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CModelTimeinfo	// sizeof = 0x4
{
	BYTE timeOn;
	BYTE timeOff;
	WORD pairedModel;
};
#pragma pack(pop)

static_assert(sizeof(CModelTimeinfo) == 0x4, "Incorrect struct size: CModelTimeinfo");