// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct CModelBaseVtbl	// sizeof = 0x3C
{
	DWORD __destructor;
	DWORD _m04;
	DWORD _m08;
	DWORD _m0C;
	DWORD getType;
	DWORD getTimeinfo;
	DWORD init;
	DWORD clear;
	DWORD deleteRwObject;
	DWORD getRwObjectType;
	DWORD createInstanceSetMM;
	DWORD createInstance;
	DWORD initIfpName;
	DWORD initIfp;
	DWORD getIfpIndex;
};

static_assert(sizeof(CModelBaseVtbl) == 0x3C, "Incorrect struct size: CModelBaseVtbl");