// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CBaseModelInfo.h"


#pragma pack(push, 1)
struct CModelObjs	// sizeof = 0x20
{
	CBaseModelInfo __parent;
};
#pragma pack(pop)

static_assert(sizeof(CModelObjs) == 0x20, "Incorrect struct size: CModelObjs");