// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelHier.h"


#pragma pack(push, 1)
struct CModelWeap	// sizeof = 0x28
{
	CModelHier __parent;
	WORD field_24;
	WORD field_26;
};
#pragma pack(pop)

static_assert(sizeof(CModelWeap) == 0x28, "Incorrect struct size: CModelWeap");