// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CNodeRoute	// sizeof = 0x24
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
};
#pragma pack(pop)

static_assert(sizeof(CNodeRoute) == 0x24, "Incorrect struct size: CNodeRoute");