// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct ColDataHeader	// sizeof = 0x30
{
	WORD numberOfSpheres;
	WORD numberOfBoxes;
	WORD numberOfFaces;
	BYTE number1;
	BYTE flags;
	DWORD spheres;
	DWORD boxes;
	DWORD ptr1;
	DWORD meshVertices;
	DWORD meshFaces;
	DWORD ptr2;
	DWORD numberOfShadowMeshFaces;
	DWORD numberOfShadowMeshVertice;
	DWORD shadowMeshVertices;
	DWORD shadowMeshFaces;
};
#pragma pack(pop)

static_assert(sizeof(ColDataHeader) == 0x30, "Incorrect struct size: ColDataHeader");