// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct ColFileHeader	// sizeof = 0x20
{
	DWORD fourcc;
	DWORD dataSize;
	BYTE modelname[20];
	DWORD _unused;
};
#pragma pack(pop)

static_assert(sizeof(ColFileHeader) == 0x20, "Incorrect struct size: ColFileHeader");