// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct ColInitData	// sizeof = 0x1C
{
	DWORD field_0;
	DWORD animID;
	DWORD field_4;
	RwV3D center;
	DWORD radius;
};
#pragma pack(pop)

static_assert(sizeof(ColInitData) == 0x1C, "Incorrect struct size: ColInitData");