// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CollisionLink	// sizeof = 0xC
{
	DWORD ptr;
	DWORD next;
	DWORD prev;
};
#pragma pack(pop)

static_assert(sizeof(CollisionLink) == 0xC, "Incorrect struct size: CollisionLink");