// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct ColSphere1	// sizeof = 0x14
{
	DWORD radius;
	RwV3D center;
	BYTE material;
	BYTE flag;
	BYTE field_12;
	BYTE _f2;
};
#pragma pack(pop)

static_assert(sizeof(ColSphere1) == 0x14, "Incorrect struct size: ColSphere1");