// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "ColSurface.h"
#include "RwSphere.h"


#pragma pack(push, 1)
struct ColSphere	// sizeof = 0x14
{
	RwSphere sphere;
	ColSurface surface;
};
#pragma pack(pop)

static_assert(sizeof(ColSphere) == 0x14, "Incorrect struct size: ColSphere");