// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct ColSurface	// sizeof = 0x4
{
	BYTE material;
	BYTE flag;
	BYTE field_2;
	BYTE light;
};
#pragma pack(pop)

static_assert(sizeof(ColSurface) == 0x4, "Incorrect struct size: ColSurface");