// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct ComponentLinks	// sizeof = 0x7C
{
	WORD component1[30];
	WORD component2[30];
	DWORD componentCount;
};

static_assert(sizeof(ComponentLinks) == 0x7C, "Incorrect struct size: ComponentLinks");