// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "PadData.h"


#pragma pack(push, 1)
struct CPad	// sizeof = 0x134
{
	PadData padState;
	PadData prevPadState;
	WORD field_60[10];
	DWORD field_74;
	PadData padStateKbd1;
	PadData padStateKbd2;
	PadData field_D8;
	BYTE field_108;
	BYTE field_109;
	WORD field_10A;
	WORD field_10C;
	WORD field_10E;
	BYTE field_110;
	DWORD field_111;
	BYTE field_115;
	BYTE field_116;
	BYTE menuActive;
	BYTE field_118;
	BYTE field_119;
	BYTE field_11A;
	BYTE field_11B;
	BYTE field_11C;
	BYTE field_11D;
	BYTE field_11E;
	BYTE field_11F;
	DWORD padQueryTime;
	DWORD field_124;
	DWORD field_128;
	DWORD field_12C;
	BYTE field_130;
	BYTE field_131;
	WORD field_132;
};
#pragma pack(pop)

static_assert(sizeof(CPad) == 0x134, "Incorrect struct size: CPad");