// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPadConfig	// sizeof = 0x10
{
	DWORD field_0;
	BYTE present;
	BYTE zaxisPresent;
	BYTE rzAxisPresent;
	BYTE __align;
	DWORD vendorId;
	DWORD productId;
};
#pragma pack(pop)

static_assert(sizeof(CPadConfig) == 0x10, "Incorrect struct size: CPadConfig");