// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CParticleData__LListHead.h"
#include "SimpleBuffer.h"


#pragma pack(push, 1)
struct CParticleData	// sizeof = 0xB8
{
	CParticleData__LListHead field_0;
	CParticleData__LListHead field_C;
	DWORD field_18;
	CParticleData__LListHead field_1C;
	DWORD txdIndex;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD field_38;
	DWORD field_3C;
	DWORD field_40;
	DWORD field_44;
	DWORD field_48;
	DWORD field_4C;
	DWORD field_50;
	DWORD field_54;
	DWORD field_58;
	DWORD field_5C;
	DWORD field_60;
	DWORD field_64;
	DWORD field_68;
	DWORD field_6C;
	DWORD field_70;
	DWORD field_74;
	DWORD field_78;
	DWORD field_7C;
	DWORD field_80;
	DWORD field_84;
	DWORD currentMatrix;
	DWORD matrices[8];
	SimpleBuffer _buffer;
};
#pragma pack(pop)

static_assert(sizeof(CParticleData) == 0xB8, "Incorrect struct size: CParticleData");