// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CParticleData__LListHead	// sizeof = 0xC
{
	DWORD listHead;
	DWORD field_4;
	DWORD count;
};
#pragma pack(pop)

static_assert(sizeof(CParticleData__LListHead) == 0xC, "Incorrect struct size: CParticleData__LListHead");