// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CParkedGenerator	// sizeof = 0x20
{
	WORD model;
	BYTE color1;
	BYTE color2;
	WORD x;
	WORD y;
	WORD z;
	BYTE angle;
	BYTE alarm;
	BYTE doorLock;
	BYTE RelatedToPlayerOwned;
	WORD field_E;
	WORD moneyValue;
	WORD field_12;
	DWORD time;
	WORD field_18;
	WORD enabled;
	BYTE field_1C;
	BYTE allocated;
	WORD field_1E;
};
#pragma pack(pop)

static_assert(sizeof(CParkedGenerator) == 0x20, "Incorrect struct size: CParkedGenerator");