// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPath	// sizeof = 0x10
{
	DWORD number;
	DWORD pData;
	DWORD field_8;
	BYTE usageCount;
	BYTE __pad[3];
};
#pragma pack(pop)

static_assert(sizeof(CPath) == 0x10, "Incorrect struct size: CPath");