// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedTasks	// sizeof = 0x30
{
	DWORD m_primaryTasks[5];
	DWORD m_secondaryTasks[6];
	DWORD m_pPed;
};
#pragma pack(pop)

static_assert(sizeof(CPedTasks) == 0x30, "Incorrect struct size: CPedTasks");