// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedIntelligence__struct_34	// sizeof = 0x34
{
	DWORD ped;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	BYTE field_1C;
	BYTE field_1D;
	WORD field_1E;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
};
#pragma pack(pop)

static_assert(sizeof(CPedIntelligence__struct_34) == 0x34, "Incorrect struct size: CPedIntelligence__struct_34");