// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedGroups	// sizeof = 0x18
{
	WORD m_awUniqueID[8];
	BYTE m_abUsed[8];
};
#pragma pack(pop)

static_assert(sizeof(CPedGroups) == 0x18, "Incorrect struct size: CPedGroups");