// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedEventList	// sizeof = 0x180
{
	DWORD eventIds[96];
};
#pragma pack(pop)

static_assert(sizeof(CPedEventList) == 0x180, "Incorrect struct size: CPedEventList");