// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedAcquaintance	// sizeof = 0x14
{
	DWORD respect;
	DWORD like;
	DWORD field_8;
	DWORD dislike;
	DWORD hate;
};
#pragma pack(pop)

static_assert(sizeof(CPedAcquaintance) == 0x14, "Incorrect struct size: CPedAcquaintance");