// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAiTimer.h"
#include "CPedIntelligence__struct_3.h"


#pragma pack(push, 1)
struct CPedIntelligence__struct_18C	// sizeof = 0xD4
{
	DWORD field_0;
	CAiTimer field_4;
	CAiTimer field_10;
	CPedIntelligence__struct_3 field_1C;
	CAiTimer field_AC;
	BYTE field_B8;
	BYTE field_B9;
	BYTE field_BA;
	BYTE _undefined_0;
	CAiTimer field_BC;
	CAiTimer field_C8;
};
#pragma pack(pop)

static_assert(sizeof(CPedIntelligence__struct_18C) == 0xD4, "Incorrect struct size: CPedIntelligence__struct_18C");