// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CEventGroup.h"
#include "CPedIntelligence__struct_18C.h"
#include "CPedIntelligence__struct_264.h"
#include "CAiTimer.h"
#include "CPedTasks.h"
#include "CPedIntelligence__struct_34.h"
#include "CEntityScanner.h"


#pragma pack(push, 1)
struct CPedIntelligence	// sizeof = 0x294
{
	DWORD m_pPed;
	CPedTasks m_pedTasks;
	CPedIntelligence__struct_34 field_34;
	CEventGroup m_pedEvents;
	DWORD m_dwDefaultDecisionMaker;
	DWORD _DM_00;
	DWORD m_fMeleeAccuracyA;
	DWORD m_fMeleeAccuracyB;
	DWORD m_dwDmNumPedsToScan;
	DWORD m_fDmRadius;
	DWORD field_CC;
	BYTE field_D0;
	BYTE eventId;
	BYTE eventPriority;
	BYTE field_D3;
	CEntityScanner n_vehicleScanner;
	CEntityScanner m_pedScanner;
	BYTE field_174;
	BYTE _undefined_0;
	BYTE _undefined_1;
	BYTE _undefined_2;
	CAiTimer field_178;
	DWORD field_184;
	BYTE field_188;
	BYTE _undefined_3;
	BYTE _undefined_4;
	BYTE _undefined_5;
	CPedIntelligence__struct_18C field_18C;
	BYTE field_260;
	BYTE _undefined_6;
	BYTE _undefined_7;
	BYTE _undefined_8;
	CPedIntelligence__struct_264 field_264;
	DWORD field_274;
	DWORD field_278;
	BYTE _undefined_9;
	BYTE _undefined_10;
	BYTE _undefined_11;
	BYTE _undefined_12;
	BYTE _undefined_13;
	BYTE _undefined_14;
	BYTE _undefined_15;
	BYTE _undefined_16;
	BYTE _undefined_17;
	BYTE _undefined_18;
	BYTE _undefined_19;
	BYTE _undefined_20;
	DWORD field_288;
	DWORD field_28C;
	DWORD field_290;
};
#pragma pack(pop)

static_assert(sizeof(CPedIntelligence) == 0x294, "Incorrect struct size: CPedIntelligence");