// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CPedIntelligence__struct_264	// sizeof = 0x10
{
	RwV3D field_0;
	WORD field_C;
	WORD field_E;
};
#pragma pack(pop)

static_assert(sizeof(CPedIntelligence__struct_264) == 0x10, "Incorrect struct size: CPedIntelligence__struct_264");