// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedStats	// sizeof = 0x34
{
	DWORD nNum;
	BYTE sName[24];
	DWORD fFleeDistance;
	DWORD fHeadingChangeRate;
	BYTE bFear;
	BYTE bTemper;
	BYTE bLawfullness;
	BYTE bSexiness;
	DWORD fAttackStrenght;
	DWORD fDefendWeakness;
	WORD wShootingRate;
	BYTE bDecision;
	BYTE field_33;
};
#pragma pack(pop)

static_assert(sizeof(CPedStats) == 0x34, "Incorrect struct size: CPedStats");