// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedEvent_DM_EventData	// sizeof = 0x3C
{
	DWORD field_0[6];
	BYTE field_18;
	BYTE field_19;
	BYTE field_1A;
	BYTE field_1B;
	DWORD field_1C[4];
	DWORD field_2C;
	BYTE field_30;
	BYTE field_31;
	WORD field_32[4];
	WORD field_3A;
};
#pragma pack(pop)

static_assert(sizeof(CPedEvent_DM_EventData) == 0x3C, "Incorrect struct size: CPedEvent_DM_EventData");