// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedTaskAssignment	// sizeof = 0x14
{
	DWORD nTaskId;
	DWORD field_4;
	DWORD field_8;
	DWORD pPed;
	DWORD _status;
};
#pragma pack(pop)

static_assert(sizeof(CPedTaskAssignment) == 0x14, "Incorrect struct size: CPedTaskAssignment");