// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPedSound	// sizeof = 0x100
{
	DWORD __vmt;
	DWORD pPed;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	BYTE field_14[124];
	BYTE field_90;
	BYTE field_91;
	WORD voiceType;
	WORD voice3;
	WORD field_96;
	BYTE field_98;
	BYTE field_99;
	BYTE field_9A;
	BYTE field_9B;
	BYTE field_9C;
	BYTE field_9D;
	BYTE field_9E;
	BYTE field_9F;
	DWORD field_A0;
	WORD field_A4;
	WORD field_A6;
	WORD field_A8;
	WORD field_AA;
	DWORD field_AC;
	WORD field_B0;
	WORD field_B2;
	DWORD field_B4[19];
};
#pragma pack(pop)

static_assert(sizeof(CPedSound) == 0x100, "Incorrect struct size: CPedSound");