// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CPedAcquaintance.h"


#pragma pack(push, 1)
struct CPedAcquaintances	// sizeof = 0x284
{
	DWORD count;
	CPedAcquaintance objects[32];
};
#pragma pack(pop)

static_assert(sizeof(CPedAcquaintances) == 0x284, "Incorrect struct size: CPedAcquaintances");