// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAiTimer.h"


#pragma pack(push, 1)
struct CPedIntelligence__struct_3	// sizeof = 0x90
{
	BYTE field_0;
	BYTE _undefined_0;
	BYTE _undefined_1;
	BYTE _undefined_2;
	CAiTimer field_4;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18[10];
	DWORD field_40[10];
	DWORD field_68[10];
};
#pragma pack(pop)

static_assert(sizeof(CPedIntelligence__struct_3) == 0x90, "Incorrect struct size: CPedIntelligence__struct_3");