// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPickup	// sizeof = 0x20
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD regenerationTime;
	WORD X;
	WORD Y;
	WORD Z;
	WORD field_16;
	WORD wModelID;
	WORD wGeneration;
	BYTE nbPickupType;
	BYTE field_1D;
	BYTE field_1E;
	BYTE field_1F;
};
#pragma pack(pop)

static_assert(sizeof(CPickup) == 0x20, "Incorrect struct size: CPickup");