// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPlayerData_2	// sizeof = 0x270
{
	DWORD field_0[6];
	DWORD field_18[128];
	WORD field_218;
	WORD field_21A;
	WORD field_21C;
	WORD field_21E;
	WORD field_220;
	WORD field_222;
	WORD field_224;
	WORD field_226;
	WORD field_228;
	WORD field_22A;
	WORD field_22C;
	WORD field_22E;
	WORD field_230;
	WORD field_232;
	WORD field_234;
	WORD field_236;
	WORD field_238;
	WORD field_23A;
	WORD field_23C;
	WORD field_23E;
	WORD field_240;
	WORD field_242;
	WORD field_244;
	WORD field_246;
	WORD field_248;
	WORD field_24A;
	WORD field_24C;
	WORD field_24E;
	WORD field_250;
	WORD field_252;
	WORD field_254;
	WORD field_256;
	WORD field_258;
	WORD field_25A;
	WORD field_25C;
	WORD field_25E;
	WORD field_260;
	WORD field_262;
	WORD field_264;
	WORD field_266;
	WORD field_268;
	WORD field_26A;
	WORD field_26C;
	WORD field_26E;
};
#pragma pack(pop)

static_assert(sizeof(CPlayerData_2) == 0x270, "Incorrect struct size: CPlayerData_2");