// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAutomobile.h"


#pragma pack(push, 1)
struct CPlane	// sizeof = 0xA04
{
	CAutomobile __parent;
	DWORD field_988;
	DWORD field_98C;
	DWORD field_990;
	DWORD field_994;
	DWORD field_998;
	DWORD field_99C;
	DWORD field_9A0;
	DWORD field_9A4;
	DWORD MaxAltitude;
	DWORD field_9AC;
	DWORD MinAltiude;
	DWORD flyHeading;
	DWORD flyHeading2;
	DWORD field_9BC;
	DWORD Sometimer;
	DWORD field_9C4;
	DWORD field_9C8;
	DWORD LandingGearPosition;
	DWORD field_9D0;
	DWORD field_9D4;
	DWORD field_9D8;
	DWORD field_9DC;
	DWORD field_9E0;
	DWORD field_9E4;
	DWORD pJettrusParticles[4];
	DWORD field_9F8;
	DWORD field_9FC;
	DWORD IsSmoking;
};
#pragma pack(pop)

static_assert(sizeof(CPlane) == 0xA04, "Incorrect struct size: CPlane");