// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CPlayerData	// sizeof = 0xAC
{
	DWORD pWanted;
	DWORD pClothesInfo;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD crimeSensitivity;
	DWORD fTimeCanRun;
	DWORD field_1C;
	BYTE field_20;
	BYTE field_21;
	WORD __pad1;
	DWORD Idle2StartScreenSaver;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD recruitesIndex;
	DWORD nAdrenalineTime;
	BYTE _isDrunk;
	BYTE field_41;
	BYTE field_42;
	BYTE field_43;
	DWORD fBreathMeter;
	DWORD field_48;
	DWORD field_4C;
	DWORD field_50;
	DWORD field_54;
	DWORD field_58;
	DWORD field_5C;
	DWORD m_fMinigunRotation;
	DWORD field_64;
	DWORD field_68;
	DWORD field_6C;
	DWORD field_70;
	RwV3D field_74;
	DWORD field_80;
	BYTE field_84;
	BYTE field_85;
	BYTE field_86;
	BYTE field_87;
	WORD field_88;
	WORD field_8A;
	BYTE field_8C;
	BYTE field_8D;
	BYTE field_8E;
	BYTE field_8F;
	DWORD field_90;
	DWORD field_94;
	DWORD field_98;
	DWORD lastModelShot;
	DWORD field_A0;
	DWORD field_A4;
	DWORD field_A8;
};
#pragma pack(pop)

static_assert(sizeof(CPlayerData) == 0xAC, "Incorrect struct size: CPlayerData");