// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "CPlayerData.h"


#pragma pack(push, 1)
struct CPlayer	// sizeof = 0x190
{
	DWORD pPed;
	CPlayerData data;
	DWORD vehicle;
	DWORD field_B4;
	DWORD money;
	DWORD field_BC;
	DWORD field_C0;
	DWORD field_C4;
	DWORD field_C8;
	DWORD field_CC;
	DWORD field_D0;
	BYTE field_D4;
	BYTE field_D5;
	WORD __pad1;
	DWORD field_D8;
	BYTE isWastedBusted;
	BYTE field_DD;
	BYTE field_DE;
	BYTE field_DF;
	DWORD field_E0;
	DWORD field_E4;
	DWORD field_E8;
	DWORD field_EC;
	DWORD field_F0;
	DWORD field_F4;
	DWORD field_F8;
	DWORD field_FC;
	DWORD field_100;
	DWORD field_104;
	DWORD field_108;
	DWORD field_10C;
	DWORD field_110;
	DWORD field_114;
	DWORD trappedInCar;
	DWORD field_11C;
	DWORD field_120;
	DWORD field_124;
	DWORD field_128;
	DWORD field_12C;
	WORD field_130;
	BYTE _undefined_0;
	BYTE _undefined_1;
	DWORD field_134;
	DWORD field_138;
	DWORD field_13C;
	DWORD field_140;
	WORD field_144;
	BYTE _undefined_2;
	BYTE _undefined_3;
	DWORD field_148;
	BYTE infiniteRun;
	BYTE fastReload;
	BYTE field_14E;
	BYTE field_14F;
	BYTE maxArmour;
	BYTE field_151;
	BYTE field_152;
	BYTE field_153;
	WORD field_154;
	WORD field_156;
	RwV3D field_158;
	BYTE skinName[32];
	DWORD skinTexture;
	BYTE field_188;
	BYTE _undefined_4;
	BYTE _undefined_5;
	BYTE _undefined_6;
	DWORD field_18C;
};
#pragma pack(pop)

static_assert(sizeof(CPlayer) == 0x190, "Incorrect struct size: CPlayer");