// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CPtrNodeSingle	// sizeof = 0x8
{
	DWORD ptr;
	DWORD next;
};
#pragma pack(pop)

static_assert(sizeof(CPtrNodeSingle) == 0x8, "Incorrect struct size: CPtrNodeSingle");