// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CRect.h"


#pragma pack(push, 1)
struct CQuadTreeNode	// sizeof = 0x28
{
	CRect field_0;
	DWORD field_10;
	DWORD children[4];
	DWORD field_24;
};
#pragma pack(pop)

static_assert(sizeof(CQuadTreeNode) == 0x28, "Incorrect struct size: CQuadTreeNode");