// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CRect	// sizeof = 0x10
{
	DWORD l;
	DWORD t;
	DWORD r;
	DWORD b;
};
#pragma pack(pop)

static_assert(sizeof(CRect) == 0x10, "Incorrect struct size: CRect");