// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "SReference.h"


#pragma pack(push, 1)
struct CReferences	// sizeof = 0x5DC4
{
	SReference m_refs[3000];
	DWORD m_pFreeList;
};
#pragma pack(pop)

static_assert(sizeof(CReferences) == 0x5DC4, "Incorrect struct size: CReferences");