// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwRGBA.h"
#include "RwV3D.h"


#pragma pack(push, 1)
struct CRegisteredMotionBlurStreak	// sizeof = 0x54
{
	DWORD entity;
	RwRGBA color;
	RwV3D startPoint;
	RwV3D field_14;
	RwV3D field_20;
	RwV3D endPoint;
	RwV3D field_38;
	RwV3D field_44;
	BYTE existFlag;
	BYTE field_51;
	BYTE field_52;
	BYTE field_53;
};
#pragma pack(pop)

static_assert(sizeof(CRegisteredMotionBlurStreak) == 0x54, "Incorrect struct size: CRegisteredMotionBlurStreak");