// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CRoadblock	// sizeof = 0x1C
{
	RwV3D cornerA;
	RwV3D cornerB;
	BYTE active;
	BYTE field_19;
	BYTE type;
	BYTE field_1B;
};
#pragma pack(pop)

static_assert(sizeof(CRoadblock) == 0x1C, "Incorrect struct size: CRoadblock");