// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "ScriptVar.h"

#pragma pack(push,1)
struct CRunningScript	// sizeof = 0xE0
{
	CRunningScript* next;
	CRunningScript* prev;
	char threadName[8];
	DWORD baseIp;
	DWORD _ip;
	DWORD gosub_stack[8];
	WORD gosub_index;
	WORD field_3A;
	ScriptVar tls[32];
	ScriptVar timers[2];
	BYTE isActive;
	BYTE condResult;
	BYTE missionFlag;
	BYTE isExternal;
	BYTE field_C8;
	BYTE field_C9;
	BYTE field_CA;
	BYTE field_CB;
	DWORD wakeTime;
	WORD logicalOp;
	BYTE notFlag;
	BYTE wastedBustedCheckEnabled;
	BYTE wastedOrBusted;
	BYTE field_D5;
	WORD field_D6;
	DWORD sceneSkipIP;
	BYTE isMission;
	WORD CLEO_scmFunction;
	BYTE CLEO_isCustom;
};
#pragma pack(pop)

static_assert(sizeof(CRunningScript) == 0xE0, "Incorrect struct size: CRunningScript");