// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct CScriptThread	// sizeof = 0xE0
{
	DWORD next;
	DWORD prev;
	BYTE threadName[8];
	DWORD baseIp;
	DWORD _ip;
	DWORD stack[8];
	WORD _sp;
	WORD field_3A;
	DWORD _tls[34];
	BYTE isActive;
	BYTE condResult;
	BYTE field_C6;
	BYTE external;
	BYTE field_C8;
	BYTE field_C9;
	BYTE field_CA;
	BYTE field_CB;
	DWORD wakeTime;
	WORD logicalOp;
	BYTE notFlag;
	BYTE wastedBustedCheckEnabled;
	BYTE wastedOrBusted;
	BYTE field_D5;
	WORD field_D6;
	DWORD sceneSkip;
	BYTE field_DC;
	BYTE field_DD;
	BYTE field_DE;
	BYTE field_DF;
};

static_assert(sizeof(CScriptThread) == 0xE0, "Incorrect struct size: CScriptThread");