// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CScriptSequence	// sizeof = 0x4
{
	BYTE bUsed;
	BYTE _undefined_0;
	WORD wUniqueID;
};
#pragma pack(pop)

static_assert(sizeof(CScriptSequence) == 0x4, "Incorrect struct size: CScriptSequence");