// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CScriptSphere	// sizeof = 0x18
{
	BYTE bUsed;
	BYTE field_1;
	WORD wUniqueID;
	DWORD field_4;
	RwV3D vCoords;
	DWORD fRadius;
};
#pragma pack(pop)

static_assert(sizeof(CScriptSphere) == 0x18, "Incorrect struct size: CScriptSphere");