// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CScriptRequestedModel	// sizeof = 0x1C
{
	BYTE szModelName[24];
	DWORD dwModelIndex;
};
#pragma pack(pop)

static_assert(sizeof(CScriptRequestedModel) == 0x1C, "Incorrect struct size: CScriptRequestedModel");