// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CSearchlight	// sizeof = 0x7C
{
	BYTE bUsed;
	BYTE field_1;
	BYTE field_2;
	BYTE enableShadow;
	WORD wUniqueID;
	WORD field_6;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD field_38;
	DWORD field_3C;
	DWORD field_40;
	DWORD attached;
	DWORD follow;
	DWORD tower;
	DWORD housing;
	DWORD bulb;
	DWORD _rwv3d;
	RwV3D field_5C;
	DWORD field_68;
	DWORD field_6C;
	DWORD field_70;
	DWORD field_74;
	DWORD field_78;
};
#pragma pack(pop)

static_assert(sizeof(CSearchlight) == 0x7C, "Incorrect struct size: CSearchlight");