// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CShoppingItemPrice	// sizeof = 0x8
{
	DWORD id;
	DWORD price;
};
#pragma pack(pop)

static_assert(sizeof(CShoppingItemPrice) == 0x8, "Incorrect struct size: CShoppingItemPrice");