// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CStatusText	// sizeof = 0x44
{
	DWORD globalVar;
	DWORD field_4;
	BYTE gxtEntry[8];
	WORD field_10;
	WORD lineNumber;
	BYTE field_14[8];
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	WORD field_28;
	BYTE field_2A;
	BYTE field_2B;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	BYTE field_38;
	BYTE field_39;
	BYTE field_3A;
	BYTE field_3B;
	BYTE field_3C;
	BYTE field_3D;
	BYTE field_3E;
	BYTE flashingFlag;
	BYTE field_40;
	BYTE __pad[3];
};
#pragma pack(pop)

static_assert(sizeof(CStatusText) == 0x44, "Incorrect struct size: CStatusText");