// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "0x4.h"
#include "0x2.h"
#include "0x40.h"
#include "0x8.h"
#include "0x80.h"
#include "0x20.h"
#include "0x10.h"


#pragma pack(push, 1)
struct CStoredCar	// sizeof = 0x40
{
	RwV3D pos;
	DWORD handling_flags;
	BYTE flags;
	0x2 ;[=];
	0x4 ;[=];
	0x8 ;[=];
	0x10 ;[=];
	0x20 ;[=];
	0x40 ;[=];
	0x80 ;[=];
	BYTE field_11;
	WORD model;
	WORD carmods[15];
	BYTE colour[4];
	BYTE radio_station;
	BYTE extra1;
	BYTE extra2;
	BYTE bomb_type;
	BYTE paintjob;
	BYTE nitro_count;
	BYTE angleX;
	BYTE angleY;
	BYTE angleZ;
	BYTE field_3F;
};
#pragma pack(pop)

static_assert(sizeof(CStoredCar) == 0x40, "Incorrect struct size: CStoredCar");