// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CStoredCar.h"


#pragma pack(push, 1)
struct CStoredCars	// sizeof = 0x100
{
	CStoredCar cars[4];
};
#pragma pack(pop)

static_assert(sizeof(CStoredCars) == 0x100, "Incorrect struct size: CStoredCars");