// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CStreamSector	// sizeof = 0x8
{
	DWORD ptrList1;
	DWORD ptrList2;
};
#pragma pack(pop)

static_assert(sizeof(CStreamSector) == 0x8, "Incorrect struct size: CStreamSector");