// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CString	// sizeof = 0x8
{
	BYTE field_0[8];
};
#pragma pack(pop)

static_assert(sizeof(CString) == 0x8, "Incorrect struct size: CString");