// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CStreamingChannel	// sizeof = 0x98
{
	DWORD aStreamStatus;
	DWORD iLoadingLevel;
	DWORD iBlockOffset;
	DWORD iBlockCount;
	DWORD 0_OnBeginRead;
	DWORD fromGetStreamStatus;
	DWORD streamNum;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD field_38;
	DWORD field_3C;
	DWORD field_40;
	DWORD field_44;
	DWORD field_48;
	DWORD field_4C;
	DWORD field_50;
	DWORD field_54;
	DWORD field_58;
	DWORD field_5C;
	DWORD field_60;
	DWORD field_64;
	DWORD field_68;
	DWORD field_6C;
	DWORD field_70;
	DWORD field_74;
	DWORD field_78;
	DWORD field_7C;
	DWORD field_80;
	DWORD field_84;
	DWORD field_88;
	DWORD field_8C;
	DWORD field_90;
	DWORD field_94;
};
#pragma pack(pop)

static_assert(sizeof(CStreamingChannel) == 0x98, "Incorrect struct size: CStreamingChannel");