// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CSurfaceType	// sizeof = 0xC
{
	BYTE tyreGrip;
	BYTE wetGrip;
	WORD pad;
	DWORD flags1;
	DWORD flags2;
};
#pragma pack(pop)

static_assert(sizeof(CSurfaceType) == 0xC, "Incorrect struct size: CSurfaceType");