// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAiTimer.h"
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskSimplePause	// sizeof = 0x18
{
	CTask __parent;
	CAiTimer m_timer;
	DWORD m_nTime;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimplePause) == 0x18, "Incorrect struct size: CTaskSimplePause");