// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskComplex.h"


#pragma pack(push, 1)
struct CTaskComplexJump	// sizeof = 0x14
{
	CTaskComplex __parent;
	DWORD field_C;
	BYTE field_10;
	BYTE field_11[3];
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexJump) == 0x14, "Incorrect struct size: CTaskComplexJump");