// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskSimpleAnim.h"


#pragma pack(push, 1)
struct CTaskSimpleRunAnim	// sizeof = 0x20
{
	CTaskSimpleAnim __parent;
	DWORD field_10;
	DWORD m_dwAnimId;
	DWORD field_18;
	WORD m_eTaskId;
	WORD __pad;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleRunAnim) == 0x20, "Incorrect struct size: CTaskSimpleRunAnim");