// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskComplex.h"


#pragma pack(push, 1)
struct CTaskComplexHandsignalAnim	// sizeof = 0x15
{
	CTaskComplex __parent;
	DWORD field_C;
	DWORD field_10;
	BYTE field_14;
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexHandsignalAnim) == 0x15, "Incorrect struct size: CTaskComplexHandsignalAnim");