// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskSimpleAnim.h"
#include "CAiTimer.h"


#pragma pack(push, 1)
struct CTaskSimpleRunNamedAnim	// sizeof = 0x64
{
	CTaskSimpleAnim __parent;
	BYTE m_szAnimName[24];
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD field_38;
	DWORD animation;
	DWORD field_40;
	CAiTimer field_44;
	DWORD field_50;
	DWORD field_54;
	DWORD field_58;
	DWORD field_5C;
	DWORD field_60;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleRunNamedAnim) == 0x64, "Incorrect struct size: CTaskSimpleRunNamedAnim");