// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CAiTimer.h"
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskSimpleStandStill	// sizeof = 0x20
{
	CTask __parent;
	DWORD m_nTime;
	CAiTimer m_timer;
	BYTE field_18;
	BYTE field_19;
	BYTE _undefined_0;
	BYTE _undefined_1;
	DWORD field_1C;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleStandStill) == 0x20, "Incorrect struct size: CTaskSimpleStandStill");