// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskSimpleSetCharDecisionMaker	// sizeof = 0xC
{
	CTask __parent;
	DWORD m_dwDmHandle;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleSetCharDecisionMaker) == 0xC, "Incorrect struct size: CTaskSimpleSetCharDecisionMaker");