// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"
#include "CAiTimer.h"


#pragma pack(push, 1)
struct CTaskSimpleDriveCar	// sizeof = 0x5D
{
	CTask __parent;
	DWORD m_pVehicle;
	DWORD field_C;
	DWORD field_10;
	CAiTimer field_14;
	DWORD field_20;
	BYTE _undefined_0;
	BYTE _undefined_1;
	BYTE _undefined_2;
	BYTE _undefined_3;
	BYTE _undefined_4;
	BYTE _undefined_5;
	BYTE _undefined_6;
	BYTE _undefined_7;
	BYTE _undefined_8;
	BYTE _undefined_9;
	BYTE _undefined_10;
	BYTE _undefined_11;
	BYTE _undefined_12;
	BYTE _undefined_13;
	BYTE _undefined_14;
	BYTE _undefined_15;
	BYTE _undefined_16;
	BYTE _undefined_17;
	BYTE _undefined_18;
	BYTE _undefined_19;
	BYTE _undefined_20;
	BYTE _undefined_21;
	BYTE _undefined_22;
	BYTE _undefined_23;
	DWORD field_3C;
	DWORD field_40;
	DWORD field_44;
	BYTE _undefined_24;
	BYTE _undefined_25;
	BYTE _undefined_26;
	BYTE _undefined_27;
	DWORD field_4C;
	CAiTimer field_50;
	BYTE field_5C;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleDriveCar) == 0x5D, "Incorrect struct size: CTaskSimpleDriveCar");