// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "CTaskComplex.h"


#pragma pack(push, 1)
struct CTaskComplexEvasiveDiveAndGetUp	// sizeof = 0x21
{
	CTaskComplex __parent;
	DWORD m_pEntity;
	DWORD m_nTimeOnGround;
	RwV3D m_vDirection;
	BYTE field_20;
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexEvasiveDiveAndGetUp) == 0x21, "Incorrect struct size: CTaskComplexEvasiveDiveAndGetUp");