// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskComplex.h"


#pragma pack(push, 1)
struct CTaskComplexCarDrive	// sizeof = 0x24
{
	CTaskComplex __parent;
	DWORD m_pVehicle;
	DWORD m_fSpeed;
	DWORD field_14;
	DWORD field_18;
	BYTE field_1C;
	BYTE m_nbTrafficBehavior;
	BYTE m_nbDriverBehavior;
	BYTE field_1F;
	BYTE m_bSavedVehicleBehavior;
	BYTE field_21[3];
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexCarDrive) == 0x24, "Incorrect struct size: CTaskComplexCarDrive");