// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CTaskSimpleDriveCar_obj1	// sizeof = 0x1C
{
	RwV3D field_0;
	DWORD field_C;
	DWORD m_nTime;
	DWORD field_14;
	DWORD field_18;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleDriveCar_obj1) == 0x1C, "Incorrect struct size: CTaskSimpleDriveCar_obj1");