// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskComplex	// sizeof = 0xC
{
	CTask __parent;
	DWORD m_pSubTask;
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplex) == 0xC, "Incorrect struct size: CTaskComplex");