// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskComplexWander.h"
#include "CAiTimer.h"


#pragma pack(push, 1)
struct CTaskComplexWanderCop	// sizeof = 0x50
{
	CTaskComplexWander __parent;
	DWORD field_28;
	CAiTimer field_2C;
	DWORD field_38;
	DWORD field_3C;
	DWORD field_40;
	CAiTimer field_44;
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexWanderCop) == 0x50, "Incorrect struct size: CTaskComplexWanderCop");