// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskSimpleFight	// sizeof = 0x28
{
	CTask __parent;
	BYTE field_8;
	BYTE field_9;
	BYTE field_A;
	BYTE _undefined_0;
	DWORD m_dwIfpIndex;
	WORD field_10;
	WORD field_12;
	BYTE field_14;
	BYTE field_15;
	BYTE _undefined_1;
	BYTE _undefined_2;
	DWORD m_pEntity;
	DWORD field_1C;
	DWORD field_20;
	BYTE field_24;
	BYTE field_25;
	BYTE field_26;
	BYTE field_27;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleFight) == 0x28, "Incorrect struct size: CTaskSimpleFight");