// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskSimpleAnim.h"


#pragma pack(push, 1)
struct CTask_86D594	// sizeof = 0x70
{
	CTaskSimpleAnim __parent;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	DWORD field_38;
	DWORD field_3C;
	DWORD field_40;
	DWORD animation;
	DWORD field_48;
	DWORD field_4C;
	DWORD field_50;
	DWORD field_54;
	DWORD field_58;
	DWORD field_5C;
	DWORD field_60;
	DWORD field_64;
	BYTE field_68;
	BYTE field_69;
	BYTE _undefined_0;
	BYTE _undefined_1;
	WORD taskId;
	WORD __pad;
};
#pragma pack(pop)

static_assert(sizeof(CTask_86D594) == 0x70, "Incorrect struct size: CTask_86D594");