// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTaskSimpleStandStill.h"


#pragma pack(push, 1)
struct CTaskSimpleWaitUntilAreaCodesMatch	// sizeof = 0x24
{
	CTaskSimpleStandStill __parent;
	DWORD m_pEntity;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleWaitUntilAreaCodesMatch) == 0x24, "Incorrect struct size: CTaskSimpleWaitUntilAreaCodesMatch");