// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTask	// sizeof = 0x8
{
	DWORD __vmt;
	DWORD m_pParentTask;
};
#pragma pack(pop)

static_assert(sizeof(CTask) == 0x8, "Incorrect struct size: CTask");