// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"


#pragma pack(push, 1)
struct CTaskSimpleFightCtrl	// sizeof = 0x24
{
	CTask __parent;
	BYTE field_8;
	BYTE _undefined_0;
	WORD field_A;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleFightCtrl) == 0x24, "Incorrect struct size: CTaskSimpleFightCtrl");