// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CTask.h"
#include "CAiTimer.h"


#pragma pack(push, 1)
struct CTaskSimpleSay	// sizeof = 0x1C
{
	CTask __parent;
	DWORD m_dwAudioId;
	DWORD m_nTime;
	CAiTimer field_10;
};
#pragma pack(pop)

static_assert(sizeof(CTaskSimpleSay) == 0x1C, "Incorrect struct size: CTaskSimpleSay");