// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTaskComplexSequence	// sizeof = 0x40
{
	DWORD __vmt__;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10[8];
	DWORD field_30;
	DWORD field_34;
	BYTE field_38;
	BYTE field_39;
	BYTE field_3A;
	BYTE field_3B;
	DWORD field_3C;
};
#pragma pack(pop)

static_assert(sizeof(CTaskComplexSequence) == 0x40, "Incorrect struct size: CTaskComplexSequence");