// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CText__TDat.h"
#include "CText__Tabl.h"
#include "CText__TKey.h"


#pragma pack(push, 1)
struct CText	// sizeof = 0xA90
{
	CText__TKey tkeyMain;
	CText__TDat tdatMain;
	CText__TKey tkeyMission;
	CText__TDat tdatMission;
	BYTE field_20;
	BYTE haveTabl;
	BYTE cderrorInitialized;
	BYTE missionLoaded;
	BYTE missionName[8];
	BYTE cderrorText[256];
	CText__Tabl tabl;
};
#pragma pack(pop)

static_assert(sizeof(CText) == 0xA90, "Incorrect struct size: CText");