// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwRGBA.h"


#pragma pack(push, 1)
struct CTextDrawer	// sizeof = 0x44
{
	DWORD letterWidth;
	DWORD letterHeight;
	RwRGBA color;
	BYTE field_C;
	BYTE centered;
	BYTE withBackground;
	BYTE _pad;
	DWORD lineHeight;
	DWORD lineWidth;
	RwRGBA backgroundBoxColor;
	BYTE proportional;
	RwRGBA backgroundColor;
	BYTE shadowType;
	BYTE outlineType;
	BYTE field_23;
	BYTE alignRight;
	BYTE _pad_25;
	BYTE _pad_26;
	BYTE _pad_27;
	DWORD font;
	DWORD xPosition;
	DWORD yPosition;
	BYTE gxtEntry[8];
	DWORD param1;
	DWORD param2;
};
#pragma pack(pop)

static_assert(sizeof(CTextDrawer) == 0x44, "Incorrect struct size: CTextDrawer");