// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTexture	// sizeof = 0x4
{
	DWORD texture;
};
#pragma pack(pop)

static_assert(sizeof(CTexture) == 0x4, "Incorrect struct size: CTexture");