// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTextSprite	// sizeof = 0x3C
{
	DWORD type;
	BYTE field_4;
	BYTE field_5;
	WORD textureID;
	DWORD cornerA_X;
	DWORD cornerA_Y;
	DWORD cornerB_X;
	DWORD cornerB_Y;
	DWORD angle;
	DWORD transparentColor;
	BYTE gxt[8];
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
	DWORD field_34;
	BYTE textboxStyle;
	BYTE field_39[3];
};
#pragma pack(pop)

static_assert(sizeof(CTextSprite) == 0x3C, "Incorrect struct size: CTextSprite");