// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CText__TKey	// sizeof = 0x8
{
	DWORD data;
	DWORD size;
};
#pragma pack(pop)

static_assert(sizeof(CText__TKey) == 0x8, "Incorrect struct size: CText__TKey");