// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTexDictionaryEntry	// sizeof = 0xC
{
	DWORD dictionary;
	WORD usageCount;
	WORD parentIndex;
	DWORD hash;
};
#pragma pack(pop)

static_assert(sizeof(CTexDictionaryEntry) == 0xC, "Incorrect struct size: CTexDictionaryEntry");