// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTexCoord	// sizeof = 0x8
{
	DWORD y;
	DWORD v;
};
#pragma pack(pop)

static_assert(sizeof(CTexCoord) == 0x8, "Incorrect struct size: CTexCoord");