// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTheScripts_SBuildingLOD	// sizeof = 0x8
{
	DWORD ObjectNormal;
	DWORD ObjectLOD;
};
#pragma pack(pop)

static_assert(sizeof(CTheScripts_SBuildingLOD) == 0x8, "Incorrect struct size: CTheScripts_SBuildingLOD");