// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTheScripts_SAnimModel	// sizeof = 0x14
{
	DWORD Model;
	BYTE IFPName[16];
};
#pragma pack(pop)

static_assert(sizeof(CTheScripts_SAnimModel) == 0x14, "Incorrect struct size: CTheScripts_SAnimModel");