// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTheScripts_SSwitchCase	// sizeof = 0x8
{
	DWORD field_0;
	DWORD field_4;
};
#pragma pack(pop)

static_assert(sizeof(CTheScripts_SSwitchCase) == 0x8, "Incorrect struct size: CTheScripts_SSwitchCase");