// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTheScripts_SBuildingSwap	// sizeof = 0xC
{
	DWORD pObject;
	DWORD newModel;
	DWORD oldModel;
};
#pragma pack(pop)

static_assert(sizeof(CTheScripts_SBuildingSwap) == 0xC, "Incorrect struct size: CTheScripts_SBuildingSwap");