// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTimeCycleInfo	// sizeof = 0xAC
{
	DWORD m_fCurrentAmbientRed;
	DWORD m_fCurrentAmbientGreen;
	DWORD m_fCurrentAmbientBlue;
	DWORD m_fCurrentAmbientObjectRed;
	DWORD m_fCurrentAmbientObjectGreen;
	DWORD m_fCurrentAmbientObjectBlue;
	DWORD Unknown1;
	DWORD Unknown2;
	DWORD Unknown3;
	WORD m_nCurrentSkyTopRed;
	WORD m_nCurrentSkyTopGreen;
	WORD m_nCurrentSkyTopBlue;
	WORD m_nCurrentSkyBottomRed;
	WORD m_nCurrentSkyBottomGreen;
	WORD m_nCurrentSkyBottomBlue;
	WORD m_nCurrentSunCoreRed;
	WORD m_nCurrentSunCoreGreen;
	WORD m_nCurrentSunCoreBlue;
	WORD m_nCurrentSunCoronaRed;
	WORD m_nCurrentSunCoronaGreen;
	WORD m_nCurrentSunCoronaBlue;
	DWORD m_fCurrentSunSize;
	DWORD m_fCurrentSpriteSize;
	DWORD m_fCurrentSpriteBrightness;
	WORD m_nCurrentShadowStrength;
	WORD m_nLightShadowStrength;
	WORD m_nPoleShadowStrength;
	BYTE gap_1[2];
	DWORD m_fCurrentFarClip;
	DWORD m_fCurrentFogStart;
	DWORD m_fCurrentLightsOnGroundBrightness;
	WORD m_nCurrentLowCloudsRed;
	WORD m_nCurrentLowCloudsGreen;
	WORD m_nCurrentLowCloudsBlue;
	WORD m_nCurrentFluffyCloudsBottomRed;
	WORD m_nCurrentFluffyCloudsBottomGreen;
	WORD m_nCurrentFluffyCloudsBottomBlue;
	DWORD m_nCurrentWaterRed;
	DWORD m_nCurrentWaterGreen;
	DWORD m_nCurrentWaterBlue;
	DWORD m_nCurrentWaterAlpha;
	DWORD m_nCurrentColourCorrectRed;
	DWORD m_nCurrentColourCorrectGreen;
	DWORD m_nCurrentColourCorrectBlue;
	DWORD m_nCurrentColourCorrectAlpha;
	DWORD m_nCurrentColourAddRed;
	DWORD m_nCurrentColourAddGreen;
	DWORD m_nCurrentColourAddBlue;
	DWORD m_nCurrentColourAddAlpha;
	DWORD m_nCurrentLowCloudsAlpha;
	DWORD m_nCurrentFluffyCloudsBottomAlpha;
	WORD m_nCurrentFluffyCloudsTopAlpha;
	BYTE gap_2[2];
	DWORD Illumination;
	DWORD Unknown1_0;
};
#pragma pack(pop)

static_assert(sizeof(CTimeCycleInfo) == 0xAC, "Incorrect struct size: CTimeCycleInfo");