// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CTriggerEntity	// sizeof = 0x8
{
	DWORD entity;
	WORD index;
	WORD __pad;
};
#pragma pack(pop)

static_assert(sizeof(CTriggerEntity) == 0x8, "Incorrect struct size: CTriggerEntity");