// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"
#include "VehicleStruct__internal.h"


#pragma pack(push, 1)
struct CVehicleStruct	// sizeof = 0x314
{
	RwV3D field_0[15];
	VehicleStruct__internal field_B4[18];
	DWORD atomics[6];
	BYTE atomicCount;
	BYTE field_30D;
	WORD field_30E;
	DWORD field_310;
};
#pragma pack(pop)

static_assert(sizeof(CVehicleStruct) == 0x314, "Incorrect struct size: CVehicleStruct");