// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct CWantedCops	// sizeof = 0x1C
{
	DWORD field_0;
	DWORD vmt_ped;
	DWORD field_8;
	RwV3D pos;
	DWORD field_18;
};
#pragma pack(pop)

static_assert(sizeof(CWantedCops) == 0x1C, "Incorrect struct size: CWantedCops");