// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CWantedCops.h"


#pragma pack(push, 1)
struct CWanted	// sizeof = 0x29C
{
	DWORD Chaos;
	DWORD field_4;
	DWORD field_8;
	DWORD timeWhenGotStars;
	DWORD field_10;
	DWORD field_14;
	BYTE ncops;
	BYTE maxcops;
	BYTE nhelis;
	BYTE field_1B;
	WORD field_1C;
	BYTE field_1E;
	BYTE field_1F;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD currentWantedLevel;
	DWORD maxWantedLevel;
	CWantedCops cops[16];
	DWORD cops_vmt[10];
	DWORD field_21C;
	DWORD field_220;
	DWORD field_224;
	DWORD field_228;
	DWORD field_22C;
	DWORD field_230;
	DWORD field_234;
	DWORD field_238;
	DWORD field_23C;
	DWORD field_240;
	DWORD field_244;
	DWORD field_248;
	DWORD field_24C;
	DWORD field_250;
	DWORD field_254;
	DWORD field_258;
	DWORD field_25C;
	DWORD field_260;
	DWORD field_264;
	DWORD field_268;
	DWORD field_26C;
	DWORD field_270;
	DWORD field_274;
	DWORD field_278;
	DWORD field_27C;
	DWORD field_280;
	DWORD field_284;
	DWORD field_288;
	DWORD field_28C;
	DWORD field_290;
	DWORD field_294;
	DWORD field_298;
};
#pragma pack(pop)

static_assert(sizeof(CWanted) == 0x29C, "Incorrect struct size: CWanted");