// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CWeaponSlot	// sizeof = 0x1C
{
	DWORD type;
	DWORD state;
	DWORD ammoInClip;
	DWORD ammoRemaining;
	DWORD field_10;
	BYTE field_14;
	BYTE field_15;
	BYTE field_16;
	BYTE field_17;
	DWORD particle;
};
#pragma pack(pop)

static_assert(sizeof(CWeaponSlot) == 0x1C, "Incorrect struct size: CWeaponSlot");