// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CWheelSets	// sizeof = 0x80
{
	WORD WheelSets[60];
	WORD WheelsInSet[4];
};
#pragma pack(pop)

static_assert(sizeof(CWheelSets) == 0x80, "Incorrect struct size: CWheelSets");