// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct CZoneExtraInfo	// sizeof = 0x11
{
	BYTE field_0;
	BYTE field_1;
	BYTE field_2;
	BYTE field_3;
	DWORD field_4;
	WORD field_8;
	BYTE pedgroupWealth;
	BYTE field_B;
	BYTE field_C;
	BYTE field_D;
	BYTE field_E;
	BYTE field_F;
	BYTE field_10;
};

static_assert(sizeof(CZoneExtraInfo) == 0x11, "Incorrect struct size: CZoneExtraInfo");