// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct CZone	// sizeof = 0x20
{
	BYTE name[8];
	BYTE text[8];
	WORD x1;
	WORD y1;
	WORD z1;
	WORD x2;
	WORD y2;
	WORD z2;
	WORD ZoneInfoIndex;
	BYTE type;
	BYTE level;
};
#pragma pack(pop)

static_assert(sizeof(CZone) == 0x20, "Incorrect struct size: CZone");