// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct d3d_obj1	// sizeof = 0x1C
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
};
#pragma pack(pop)

static_assert(sizeof(d3d_obj1) == 0x1C, "Incorrect struct size: d3d_obj1");