// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct DIJOYSTATE2	// sizeof = 0x110
{
	DWORD lX;
	DWORD lY;
	DWORD lZ;
	DWORD lRx;
	DWORD lRy;
	DWORD lRz;
	DWORD rglSlider[2];
	DWORD rgdwPOV[4];
	BYTE rgbButtons[128];
	DWORD lVX;
	DWORD lVY;
	DWORD lVZ;
	DWORD lVRx;
	DWORD lVRy;
	DWORD lVRz;
	DWORD rglVSlider[2];
	DWORD lAX;
	DWORD lAY;
	DWORD lAZ;
	DWORD lARx;
	DWORD lARy;
	DWORD lARz;
	DWORD rglASlider[2];
	DWORD lFX;
	DWORD lFY;
	DWORD lFZ;
	DWORD lFRx;
	DWORD lFRy;
	DWORD lFRz;
	DWORD rglFSlider[2];
};
#pragma pack(pop)

static_assert(sizeof(DIJOYSTATE2) == 0x110, "Incorrect struct size: DIJOYSTATE2");