// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct gta_scm_object_name	// sizeof = 0x1C
{
	BYTE name[24];
	DWORD index;
};
#pragma pack(pop)

static_assert(sizeof(gta_scm_object_name) == 0x1C, "Incorrect struct size: gta_scm_object_name");