// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct HudTextures	// sizeof = 0x100
{
	DWORD empty1;
	DWORD empty2;
	DWORD radar_centre;
	DWORD arrow;
	DWORD radar_north;
	DWORD radar_airYard;
	DWORD radar_ammugun;
	DWORD radar_barbers;
	DWORD radar_BIGSMOKE;
	DWORD radar_boatyard;
	DWORD radar_burgerShot;
	DWORD radar_bulldozer;
	DWORD radar_CATALINAPINK;
	DWORD radar_CESARVIAPANDO;
	DWORD radar_chicken;
	DWORD radar_CJ;
	DWORD radar_CRASH1;
	DWORD radar_diner;
	DWORD radar_emmetGun;
	DWORD radar_enemyAttack;
	DWORD radar_fire;
	DWORD radar_girlfriend;
	DWORD radar_hospitaL;
	DWORD radar_LocoSyndicate;
	DWORD radar_MADDOG;
	DWORD radar_mafiaCasino;
	DWORD radar_MCSTRAP;
	DWORD radar_modGarage;
	DWORD radar_OGLOC;
	DWORD radar_pizza;
	DWORD radar_police;
	DWORD radar_propertyG;
	DWORD radar_propertyR;
	DWORD radar_race;
	DWORD radar_RYDER;
	DWORD radar_saveGame;
	DWORD radar_school;
	DWORD radar_qmark;
	DWORD radar_SWEET;
	DWORD radar_tattoo;
	DWORD radar_THETRUTH;
	DWORD radar_waypoint;
	DWORD radar_TorenoRanch;
	DWORD radar_triads;
	DWORD radar_triadsCasino;
	DWORD radar_tshirt;
	DWORD radar_WOOZIE;
	DWORD radar_ZERO;
	DWORD radar_dateDisco;
	DWORD radar_dateDrink;
	DWORD radar_dateFood;
	DWORD radar_truck;
	DWORD radar_cash;
	DWORD radar_flag;
	DWORD radar_gym;
	DWORD radar_impound;
	DWORD radar_light;
	DWORD radar_runway;
	DWORD radar_gangB;
	DWORD radar_gangP;
	DWORD radar_gangY;
	DWORD radar_gangN;
	DWORD radar_gangG;
	DWORD radar_spray;
};
#pragma pack(pop)

static_assert(sizeof(HudTextures) == 0x100, "Incorrect struct size: HudTextures");