// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct HudTextures2	// sizeof = 0x18
{
	DWORD fist;
	DWORD siteM16;
	DWORD siterocket;
	DWORD radardisc;
	DWORD radarRingPlane;
	DWORD skipIcon;
};
#pragma pack(pop)

static_assert(sizeof(HudTextures2) == 0x18, "Incorrect struct size: HudTextures2");