// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct IGraphBuilder	// sizeof = 0x4
{
	DWORD lpVtbl;
};
#pragma pack(pop)

static_assert(sizeof(IGraphBuilder) == 0x4, "Incorrect struct size: IGraphBuilder");