// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct IMediaControlVtbl	// sizeof = 0x40
{
	DWORD QueryInterface;
	DWORD AddRef;
	DWORD Release;
	DWORD GetTypeInfoCount;
	DWORD GetTypeInfo;
	DWORD GetIDsOfNames;
	DWORD Invoke;
	DWORD Run;
	DWORD Pause;
	DWORD Stop;
	DWORD GetState;
	DWORD RenderFile;
	DWORD AddSourceFilter;
	DWORD get_FilterCollection;
	DWORD get_RegFilterCollection;
	DWORD StopWhenReady;
};
#pragma pack(pop)

static_assert(sizeof(IMediaControlVtbl) == 0x40, "Incorrect struct size: IMediaControlVtbl");