// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct IMediaEventExVtbl	// sizeof = 0x40
{
	DWORD QueryInterface;
	DWORD AddRef;
	DWORD Release;
	DWORD GetTypeInfoCount;
	DWORD GetTypeInfo;
	DWORD GetIDsOfNames;
	DWORD Invoke;
	DWORD GetEventHandle;
	DWORD GetEvent;
	DWORD WaitForCompletion;
	DWORD CancelDefaultHandling;
	DWORD RestoreDefaultHandling;
	DWORD FreeEventParams;
	DWORD SetNotifyWindow;
	DWORD SetNotifyFlags;
	DWORD GetNotifyFlags;
};
#pragma pack(pop)

static_assert(sizeof(IMediaEventExVtbl) == 0x40, "Incorrect struct size: IMediaEventExVtbl");