// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct IMediaControl	// sizeof = 0x4
{
	DWORD lpVtbl;
};
#pragma pack(pop)

static_assert(sizeof(IMediaControl) == 0x4, "Incorrect struct size: IMediaControl");