// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct JumptableLabel	// sizeof = 0x8
{
	DWORD field_0;
	DWORD field_4;
};

static_assert(sizeof(JumptableLabel) == 0x8, "Incorrect struct size: JumptableLabel");