// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct LoadedObjectInfo	// sizeof = 0x14
{
	WORD nextIndex;
	WORD prevIndex;
	WORD field_4;
	BYTE field_6;
	BYTE field_7;
	DWORD field_8;
	DWORD field_C;
	BYTE bLoaded;
	BYTE field_11[3];
};

static_assert(sizeof(LoadedObjectInfo) == 0x14, "Incorrect struct size: LoadedObjectInfo");