// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelCars.h"


#pragma pack(push, 1)
struct ModelCarsData	// sizeof = 0x282A4
{
	DWORD count;
	CModelCars objects[212];
};
#pragma pack(pop)

static_assert(sizeof(ModelCarsData) == 0x282A4, "Incorrect struct size: ModelCarsData");