// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelHier.h"


#pragma pack(push, 1)
struct ModelHierData	// sizeof = 0xCF4
{
	DWORD count;
	CModelHier objects[92];
};
#pragma pack(pop)

static_assert(sizeof(ModelHierData) == 0xCF4, "Incorrect struct size: ModelHierData");