// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelObjs.h"


#pragma pack(push, 1)
struct ModelObjsData	// sizeof = 0x6D604
{
	DWORD count;
	CModelObjs objects[14000];
};
#pragma pack(pop)

static_assert(sizeof(ModelObjsData) == 0x6D604, "Incorrect struct size: ModelObjsData");