// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelPeds.h"


#pragma pack(push, 1)
struct ModelPedsData	// sizeof = 0x49DC
{
	DWORD count;
	CModelPeds objects[278];
};
#pragma pack(pop)

static_assert(sizeof(ModelPedsData) == 0x49DC, "Incorrect struct size: ModelPedsData");