// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CModelWeap.h"


#pragma pack(push, 1)
struct ModelWeapData	// sizeof = 0x7FC
{
	DWORD count;
	CModelWeap objects[51];
};
#pragma pack(pop)

static_assert(sizeof(ModelWeapData) == 0x7FC, "Incorrect struct size: ModelWeapData");