// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct obj_8E4C24	// sizeof = 0x30
{
	WORD field_0[22];
	WORD field_2C;
	WORD __pad_2E;
};
#pragma pack(pop)

static_assert(sizeof(obj_8E4C24) == 0x30, "Incorrect struct size: obj_8E4C24");