// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CBaseModelInfo.h"


#pragma pack(push, 1)
struct obj_85BC70	// sizeof = 0x24
{
	CBaseModelInfo __parent;
	WORD field_20;
	WORD field_22;
};
#pragma pack(pop)

static_assert(sizeof(obj_85BC70) == 0x24, "Incorrect struct size: obj_85BC70");