// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CBaseModelInfo.h"


#pragma pack(push, 1)
struct obj_85BCF0	// sizeof = 0x28
{
	CBaseModelInfo __parent;
	WORD field_20;
	WORD field_22;
	WORD field_24;
	WORD field_26;
};
#pragma pack(pop)

static_assert(sizeof(obj_85BCF0) == 0x28, "Incorrect struct size: obj_85BCF0");