// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct OcclusionBox	// sizeof = 0x12
{
	WORD midX;
	WORD midY;
	WORD midZ;
	WORD widthY;
	WORD widthX;
	WORD height;
	BYTE rotation;
	BYTE rotation2;
	BYTE rotation3;
	BYTE field_F;
	WORD flags;
};
#pragma pack(pop)

static_assert(sizeof(OcclusionBox) == 0x12, "Incorrect struct size: OcclusionBox");