// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct PadData	// sizeof = 0x30
{
	WORD LeftRight;
	WORD ForwardBackward;
	WORD SpecialCtrlLeftRight;
	WORD SpecialCtrlUpDown;
	WORD Action_SecondaryFire;
	WORD PrevWeapon_ZoomIn_LookLeft;
	WORD Aim_HandBrake;
	WORD NextWeapon_ZoomOut_LookRight;
	WORD GroupControlFwd_RadioNext;
	WORD GroupControlBkw_RadioBack;
	WORD ConversationNo;
	WORD ConversationYes;
	WORD field_18;
	WORD ChangeCamera;
	WORD Jump_BrakeReserve;
	WORD EnterVehicle;
	WORD Sprint_Accelerate;
	WORD Fire;
	WORD Crouch_Horn;
	WORD LookBehind_SubMission;
	WORD field_28;
	WORD field_2A;
	WORD field_2C;
	WORD field_2E;
};
#pragma pack(pop)

static_assert(sizeof(PadData) == 0x30, "Incorrect struct size: PadData");