// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct pair	// sizeof = 0x8
{
	DWORD keycode;
	DWORD priority;
};
#pragma pack(pop)

static_assert(sizeof(pair) == 0x8, "Incorrect struct size: pair");