// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct Placement	// sizeof = 0x10
{
	RwV3D pos;
	DWORD angle;
};
#pragma pack(pop)

static_assert(sizeof(Placement) == 0x10, "Incorrect struct size: Placement");