// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwObject.h"
#include "RpMaterialList.h"


#pragma pack(push, 1)
struct RpGeometry	// sizeof = 0x60
{
	RwObject object;
	DWORD flags;
	WORD lockedSinceLastInst;
	WORD refCount;
	DWORD numTriangles;
	DWORD numVertices;
	DWORD numMorphTargets;
	DWORD numTexCoordSets;
	RpMaterialList matList;
	DWORD triangles;
	DWORD preLitLum;
	DWORD texCoords[8];
	DWORD mesh;
	DWORD resEntry;
	DWORD morphTarget;
};
#pragma pack(pop)

static_assert(sizeof(RpGeometry) == 0x60, "Incorrect struct size: RpGeometry");