// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RpHAnimHierarchy	// sizeof = 0x24
{
	DWORD flags;
	DWORD numNodes;
	DWORD pMatrixArray;
	DWORD pMatrixArrayUnaligned;
	DWORD pNodeInfo;
	DWORD parentFrame;
	DWORD parentHierarchy;
	DWORD rootParentOffset;
	DWORD currentAnim;
};
#pragma pack(pop)

static_assert(sizeof(RpHAnimHierarchy) == 0x24, "Incorrect struct size: RpHAnimHierarchy");