// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RpLightTie	// sizeof = 0x18
{
	RwLLLink lightInWorldSector;
	DWORD light;
	RwLLLink worldSectorInLight;
	DWORD sect;
};
#pragma pack(pop)

static_assert(sizeof(RpLightTie) == 0x18, "Incorrect struct size: RpLightTie");