// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RpMaterialList	// sizeof = 0xC
{
	DWORD materials;
	DWORD numMaterials;
	DWORD space;
};
#pragma pack(pop)

static_assert(sizeof(RpMaterialList) == 0xC, "Incorrect struct size: RpMaterialList");