// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RpTie	// sizeof = 0x18
{
	RwLLLink lAtomicInWorldSector;
	DWORD apAtom;
	RwLLLink lWorldSectorInAtomic;
	DWORD worldSector;
};
#pragma pack(pop)

static_assert(sizeof(RpTie) == 0x18, "Incorrect struct size: RpTie");