// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwRGBA.h"
#include "RwBBox.h"
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RpWorldSector	// sizeof = 0x88
{
	DWORD type;
	DWORD triangles;
	DWORD vertices;
	DWORD normals;
	DWORD texCoords[8];
	RwRGBA preLitLum;
	DWORD repEntry;
	RwLLLink collAtomicsInWorldSector;
	RwLLLink lightsInWorldSector;
	RwBBox boundingBox;
	RwBBox tightBoundingBox;
	DWORD mesh;
	DWORD pipeline;
	WORD matListWindowBase;
	WORD numVertices;
	WORD numTriangles;
	WORD pad;
};
#pragma pack(pop)

static_assert(sizeof(RpWorldSector) == 0x88, "Incorrect struct size: RpWorldSector");