// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RsInputDevice.h"


#pragma pack(push, 1)
struct RsGlobalType	// sizeof = 0x3C
{
	DWORD AppName;
	DWORD MaximumWidth;
	DWORD MaximumHeight;
	DWORD frameLimit;
	DWORD quit;
	DWORD ps;
	RsInputDevice keyboard;
	RsInputDevice mouse;
	RsInputDevice pad;
};
#pragma pack(pop)

static_assert(sizeof(RsGlobalType) == 0x3C, "Incorrect struct size: RsGlobalType");