// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RsInputDevice	// sizeof = 0xC
{
	DWORD inputDeviceType;
	DWORD used;
	DWORD inputEventHandler;
};
#pragma pack(pop)

static_assert(sizeof(RsInputDevice) == 0xC, "Incorrect struct size: RsInputDevice");