// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct RtQuat	// sizeof = 0x10
{
	RwV3D imag;
	DWORD real;
};
#pragma pack(pop)

static_assert(sizeof(RtQuat) == 0x10, "Incorrect struct size: RtQuat");