// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct RwBBox	// sizeof = 0x18
{
	RwV3D sup;
	RwV3D inf;
};
#pragma pack(pop)

static_assert(sizeof(RwBBox) == 0x18, "Incorrect struct size: RwBBox");