// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwMatrix.h"
#include "RwBBox.h"
#include "RwV3D.h"
#include "RwFrustumPlane.h"
#include "RwV2D.h"
#include "RwObjectHasFrame.h"


#pragma pack(push, 1)
struct RwCamera	// sizeof = 0x184
{
	RwObjectHasFrame object;
	DWORD projectionType;
	DWORD beginUpdate;
	DWORD endUpdate;
	RwMatrix viewMatrix;
	DWORD frameBuffer;
	DWORD zBuffer;
	RwV2D viewWindow;
	RwV2D recipViewWindow;
	RwV2D viewOffset;
	DWORD nearPlane;
	DWORD farPlane;
	DWORD fogPlane;
	DWORD zScale;
	DWORD zShift;
	RwFrustumPlane frustrumPlanes[6];
	RwBBox frustrumBoundBox;
	RwV3D frustrumCorners[8];
};
#pragma pack(pop)

static_assert(sizeof(RwCamera) == 0x184, "Incorrect struct size: RwCamera");