// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwFileFunction.h"
#include "RwLinkList.h"
#include "RwMemoryFunctions.h"
#include "RwStringFunctions.h"
#include "RwDevice.h"


#pragma pack(push, 1)
struct RwEngineInstance	// sizeof = 0x158
{
	DWORD curCamera;
	DWORD curWorld;
	WORD renderFrame;
	WORD lightFrame;
	DWORD pad;
	RwDevice dOpenDevice;
	DWORD field_48;
	DWORD _cameraBeginUpdate;
	DWORD _rgbToPixel;
	DWORD _pixelToRgb;
	DWORD _rasterCreate;
	DWORD _rasterDestroy;
	DWORD _getImageFromRaster;
	DWORD _setRasterFromImage;
	DWORD _textureSetRaster;
	DWORD _findRasterFormat;
	DWORD _cameraEndUpdate;
	DWORD _setRasterContext;
	DWORD _rasterSubraster;
	DWORD _rasterClearRect;
	DWORD _rasterClear;
	DWORD _rasterLock;
	DWORD _rasterUnlock;
	DWORD _rasterRender;
	DWORD _rasterRenderScaled;
	DWORD _rasterRenderFast;
	DWORD _rasterShowRaster;
	DWORD _cameraClear;
	DWORD _hintRenderF2B;
	DWORD _rasterLockPalette;
	DWORD _rasterUnlockPalette;
	DWORD _nativeTextureGetSize;
	DWORD _nativeTextureRead;
	DWORD _nativeTextureWrite;
	DWORD _rasterGetMipLevels;
	RwLinkList dirtyFrameList;
	RwFileFunction fileFuncs;
	RwStringFunctions stringFuncs;
	RwMemoryFunctions memoryFuncs;
	DWORD memoryAlloc;
	DWORD memoryFree;
	DWORD metrics;
	DWORD engineStatus;
	DWORD resArenaSize;
};
#pragma pack(pop)

static_assert(sizeof(RwEngineInstance) == 0x158, "Incorrect struct size: RwEngineInstance");