// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwObject.h"
#include "RwMatrix.h"
#include "RwLinkList.h"
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RwFrame	// sizeof = 0xA4
{
	RwObject object;
	RwLLLink inDirtyListLink;
	RwMatrix modelling;
	RwMatrix ltm;
	RwLinkList objectList;
	DWORD child;
	DWORD next;
	DWORD root;
};
#pragma pack(pop)

static_assert(sizeof(RwFrame) == 0xA4, "Incorrect struct size: RwFrame");