// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwStringFunctions.h"
#include "RwMemoryFunctions.h"


#pragma pack(push, 1)
struct RwGlobals	// sizeof = 0x158
{
	BYTE field_1[240];
	RwStringFunctions stringFuncs;
	RwMemoryFunctions memoryFuncs;
	DWORD memoryAlloc;
	DWORD memoryFree;
	DWORD field_14C;
	DWORD engineStatus;
	DWORD field_154;
};
#pragma pack(pop)

static_assert(sizeof(RwGlobals) == 0x158, "Incorrect struct size: RwGlobals");