// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RwLinkList	// sizeof = 0x8
{
	RwLLLink link;
};
#pragma pack(pop)

static_assert(sizeof(RwLinkList) == 0x8, "Incorrect struct size: RwLinkList");