// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwLLLink	// sizeof = 0x8
{
	DWORD next;
	DWORD prev;
};
#pragma pack(pop)

static_assert(sizeof(RwLLLink) == 0x8, "Incorrect struct size: RwLLLink");