// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct RwMatrix	// sizeof = 0x40
{
	RwV3D right;
	DWORD flags;
	RwV3D top;
	DWORD pad1;
	RwV3D at;
	DWORD pad2;
	RwV3D pos;
	DWORD pad3;
};
#pragma pack(pop)

static_assert(sizeof(RwMatrix) == 0x40, "Incorrect struct size: RwMatrix");