// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwPluginRegEntry	// sizeof = 0x3C
{
	DWORD offset;
	DWORD sizeOfStruct;
	DWORD pluginID;
	DWORD readCB;
	DWORD writeCB;
	DWORD getSizeCB;
	DWORD alwaysCB;
	DWORD rightsCB;
	DWORD constructCB;
	DWORD destructCB;
	DWORD copyCB;
	DWORD errStrCB;
	DWORD nextRegEntry;
	DWORD prevregEntry;
	DWORD parentRegistry;
};
#pragma pack(pop)

static_assert(sizeof(RwPluginRegEntry) == 0x3C, "Incorrect struct size: RwPluginRegEntry");