// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwPluginRegistry	// sizeof = 0x18
{
	DWORD sizeOfStruct;
	DWORD origSizeOfStruct;
	DWORD maxSizeOfStruct;
	DWORD staticAlloc;
	DWORD firstRegEntry;
	DWORD lastRegEntry;
};
#pragma pack(pop)

static_assert(sizeof(RwPluginRegistry) == 0x18, "Incorrect struct size: RwPluginRegistry");