// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwRaster	// sizeof = 0x34
{
	DWORD parent;
	DWORD cpPixels;
	DWORD palette;
	DWORD width;
	DWORD height;
	DWORD depth;
	DWORD stride;
	WORD nOffsetX;
	WORD nOffsetY;
	BYTE cType;
	BYTE cFlags;
	BYTE privateFlags;
	BYTE cFormat;
	DWORD originalPixels;
	DWORD originalWidth;
	DWORD originalHeight;
	DWORD oriiginalStride;
};
#pragma pack(pop)

static_assert(sizeof(RwRaster) == 0x34, "Incorrect struct size: RwRaster");