// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RwResEntry	// sizeof = 0x18
{
	RwLLLink link;
	DWORD size;
	DWORD owner;
	DWORD ownerRef;
	DWORD destroyNotify;
};
#pragma pack(pop)

static_assert(sizeof(RwResEntry) == 0x18, "Incorrect struct size: RwResEntry");