// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLinkList.h"


#pragma pack(push, 1)
struct RwResources	// sizeof = 0x28
{
	DWORD maxSize;
	DWORD currentSize;
	DWORD reusageSize;
	DWORD memHeap;
	RwLinkList entriesA;
	RwLinkList entriesB;
	DWORD freeEntries;
	DWORD usedEntries;
};
#pragma pack(pop)

static_assert(sizeof(RwResources) == 0x28, "Incorrect struct size: RwResources");