// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwRGBA	// sizeof = 0x4
{
	BYTE red;
	BYTE green;
	BYTE blue;
	BYTE alpha;
};
#pragma pack(pop)

static_assert(sizeof(RwRGBA) == 0x4, "Incorrect struct size: RwRGBA");