// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


struct RwSphere	// sizeof = 0x10
{
	RwV3D center;
	float radius;
};

static_assert(sizeof(RwSphere) == 0x10, "Incorrect struct size: RwSphere");