// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwStreamFile	// sizeof = 0x24
{
	DWORD type;
	DWORD accessType;
	DWORD position;
	DWORD fpFile;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD rwOwned;
};
#pragma pack(pop)

static_assert(sizeof(RwStreamFile) == 0x24, "Incorrect struct size: RwStreamFile");