// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwStringFunctions	// sizeof = 0x44
{
	DWORD vecSprintf;
	DWORD vecVsprintf;
	DWORD vecStrcpy;
	DWORD vecStrncpy;
	DWORD vecStrcat;
	DWORD vecStrncat;
	DWORD vecStrrchr;
	DWORD vecStrchr;
	DWORD vecStrstr;
	DWORD vecStrcmp;
	DWORD vecStrncmp;
	DWORD vecStricmp;
	DWORD vecStrlen;
	DWORD vecStrupr;
	DWORD vecStrlwr;
	DWORD vecStrtok;
	DWORD vecSscanf;
};
#pragma pack(pop)

static_assert(sizeof(RwStringFunctions) == 0x44, "Incorrect struct size: RwStringFunctions");