// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RwStreamMemory	// sizeof = 0x24
{
	DWORD type;
	DWORD accessType;
	DWORD position;
	DWORD memPosition;
	DWORD memSize;
	DWORD memPtr;
	DWORD field_18;
	DWORD field_1C;
	DWORD rwOwned;
};
#pragma pack(pop)

static_assert(sizeof(RwStreamMemory) == 0x24, "Incorrect struct size: RwStreamMemory");