// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"
#include "RwLinkList.h"
#include "RwObject.h"


#pragma pack(push, 1)
struct RwTexDictionary	// sizeof = 0x18
{
	RwObject object;
	RwLinkList texturesInDict;
	RwLLLink lInInstance;
};
#pragma pack(pop)

static_assert(sizeof(RwTexDictionary) == 0x18, "Incorrect struct size: RwTexDictionary");