// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RwTexture	// sizeof = 0x58
{
	DWORD raster;
	DWORD dict;
	RwLLLink lInDictionary;
	BYTE name[32];
	BYTE mask[32];
	DWORD filterAddressing;
	DWORD refCount;
};
#pragma pack(pop)

static_assert(sizeof(RwTexture) == 0x58, "Incorrect struct size: RwTexture");