// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwLLLink.h"


#pragma pack(push, 1)
struct RwTextureModule	// sizeof = 0x34
{
	RwLLLink txdList;
	DWORD textureFreeList;
	DWORD texDictFreeList;
	DWORD currentTxd;
	DWORD readCB;
	DWORD findCB;
	DWORD enableMipmapping;
	DWORD autoMipmapping;
	DWORD field_24;
	DWORD field_28;
	DWORD rasterBuildMipmapCB;
	DWORD mipmapNameCB;
};
#pragma pack(pop)

static_assert(sizeof(RwTextureModule) == 0x34, "Incorrect struct size: RwTextureModule");