// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


struct RwV3D	// sizeof = 0xC
{
	float x;
	float y;
	float z;
};

static_assert(sizeof(RwV3D) == 0xC, "Incorrect struct size: RwV3D");