// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RxHeap	// sizeof = 0x1C
{
	DWORD superBlockSize;
	DWORD head;
	DWORD headBlocks;
	DWORD freeBlocks;
	DWORD entriesAlloced;
	DWORD entriesUsed;
	DWORD dirty;
};
#pragma pack(pop)

static_assert(sizeof(RxHeap) == 0x1C, "Incorrect struct size: RxHeap");