// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct rxHeapSuperBlockDescriptor	// sizeof = 0xC
{
	DWORD start;
	DWORD size;
	DWORD next;
};
#pragma pack(pop)

static_assert(sizeof(rxHeapSuperBlockDescriptor) == 0xC, "Incorrect struct size: rxHeapSuperBlockDescriptor");