// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct rxHeapBlockHeader	// sizeof = 0x20
{
	DWORD prev;
	DWORD next;
	DWORD size;
	DWORD freeEntry;
	DWORD _pad[4];
};
#pragma pack(pop)

static_assert(sizeof(rxHeapBlockHeader) == 0x20, "Incorrect struct size: rxHeapBlockHeader");