// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RxIoSpec.h"
#include "RxNodeMethods.h"


#pragma pack(push, 1)
struct RxNodeDefinition	// sizeof = 0x40
{
	DWORD name;
	RxNodeMethods nodeMethods;
	RxIoSpec io;
	DWORD pipelineNodePrivateDataSize;
	DWORD editable;
	DWORD InputPipesCnt;
};
#pragma pack(pop)

static_assert(sizeof(RxNodeDefinition) == 0x40, "Incorrect struct size: RxNodeDefinition");