// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RxNodeMethods	// sizeof = 0x1C
{
	DWORD nodeBody;
	DWORD nodeInit;
	DWORD nodeTerm;
	DWORD pipelineNodeInit;
	DWORD pipelineNodeTerm;
	DWORD pipelineNodeConfig;
	DWORD configMsgHandler;
};
#pragma pack(pop)

static_assert(sizeof(RxNodeMethods) == 0x1C, "Incorrect struct size: RxNodeMethods");