// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct RxObjSpace3dVertex	// sizeof = 0x24
{
	RwV3D objVertex;
	RwV3D objNormal;
	DWORD color;
	DWORD u;
	DWORD v;
};
#pragma pack(pop)

static_assert(sizeof(RxObjSpace3dVertex) == 0x24, "Incorrect struct size: RxObjSpace3dVertex");