// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct RxPipelineNodeParam	// sizeof = 0x8
{
	DWORD dataParam;
	DWORD heap;
};
#pragma pack(pop)

static_assert(sizeof(RxPipelineNodeParam) == 0x8, "Incorrect struct size: RxPipelineNodeParam");