// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwRGBA.h"


#pragma pack(push, 1)
struct RxRenderStateVector	// sizeof = 0x2C
{
	DWORD flags;
	DWORD shadeMode;
	DWORD srcBlend;
	DWORD dstBlend;
	DWORD textureRaster;
	DWORD addressModeU;
	DWORD addressModeV;
	DWORD filterMode;
	RwRGBA borderColor;
	DWORD fogType;
	RwRGBA fogColor;
};
#pragma pack(pop)

static_assert(sizeof(RxRenderStateVector) == 0x2C, "Incorrect struct size: RxRenderStateVector");