// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct SImgGTAItemInfo	// sizeof = 0x14
{
	WORD usNext;
	WORD usPrev;
	WORD uiUnknown1;
	BYTE uiUnknown2_ld;
	BYTE ucImgId;
	DWORD iBlockOffset;
	DWORD iBlockCount;
	BYTE uiLoadFlag;
	BYTE field_11[3];
};
#pragma pack(pop)

static_assert(sizeof(SImgGTAItemInfo) == 0x14, "Incorrect struct size: SImgGTAItemInfo");