// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct SimpleBuffer	// sizeof = 0xC
{
	DWORD ptr;
	DWORD size;
	DWORD position;
};
#pragma pack(pop)

static_assert(sizeof(SimpleBuffer) == 0xC, "Incorrect struct size: SimpleBuffer");