// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct SReference	// sizeof = 0x8
{
	DWORD m_pNext;
	DWORD m_pEntity;
};
#pragma pack(pop)

static_assert(sizeof(SReference) == 0x8, "Incorrect struct size: SReference");