// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "StreamingLListEntry.h"


#pragma pack(push, 1)
struct StreamedModelList	// sizeof = 0x34
{
	StreamingLListEntry usedListHead;
	StreamingLListEntry usedListTail;
	StreamingLListEntry freeListHead;
	StreamingLListEntry freeListTail;
	DWORD pEntries;
};
#pragma pack(pop)

static_assert(sizeof(StreamedModelList) == 0x34, "Incorrect struct size: StreamedModelList");