// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct struct_C92140	// sizeof = 0x10
{
	DWORD field_0;
	DWORD field_4;
	BYTE field_8;
	BYTE field_9;
	BYTE field_A;
	BYTE field_B;
	DWORD field_C;
};
#pragma pack(pop)

static_assert(sizeof(struct_C92140) == 0x10, "Incorrect struct size: struct_C92140");