// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct struc_328	// sizeof = 0x0
{
};
#pragma pack(pop)

static_assert(sizeof(struc_328) == 0x0, "Incorrect struct size: struc_328");