// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "obj_85BC70.h"


#pragma pack(push, 1)
struct struc_B1C934	// sizeof = 0x28
{
	DWORD count;
	obj_85BC70 objects;
};
#pragma pack(pop)

static_assert(sizeof(struc_B1C934) == 0x28, "Incorrect struct size: struc_B1C934");