// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwRGBA.h"


#pragma pack(push, 1)
struct struc_C71AA0	// sizeof = 0x30
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	RwRGBA field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	BYTE field_28;
	BYTE field_29;
	BYTE field_2A;
	BYTE field_2B;
	WORD field_2C;
	BYTE field_2E;
	BYTE _pad;
};
#pragma pack(pop)

static_assert(sizeof(struc_C71AA0) == 0x30, "Incorrect struct size: struc_C71AA0");