// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct struc_C1DF30_internal	// sizeof = 0x34
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
	DWORD field_20;
	DWORD field_24;
	DWORD field_28;
	DWORD field_2C;
	DWORD field_30;
};
#pragma pack(pop)

static_assert(sizeof(struc_C1DF30_internal) == 0x34, "Incorrect struct size: struc_C1DF30_internal");