// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "struc_C1DF30_internal.h"


#pragma pack(push, 1)
struct struc_C1DF30	// sizeof = 0x1A1C
{
	struc_C1DF30_internal field_0[128];
	DWORD field_1A00[3];
	DWORD field_1A0C[3];
	DWORD field_1A18;
};
#pragma pack(pop)

static_assert(sizeof(struc_C1DF30) == 0x1A1C, "Incorrect struct size: struc_C1DF30");