// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct TablEntry	// sizeof = 0xC
{
	BYTE name[8];
	DWORD offset;
};
#pragma pack(pop)

static_assert(sizeof(TablEntry) == 0xC, "Incorrect struct size: TablEntry");