// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct ThreadMLS	// sizeof = 0xC
{
	DWORD modelId;
	DWORD pThread;
	DWORD type;
};
#pragma pack(pop)

static_assert(sizeof(ThreadMLS) == 0xC, "Incorrect struct size: ThreadMLS");