// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct TransmissionGear	// sizeof = 0xC
{
	DWORD field_0;
	DWORD field_4;
	DWORD field_8;
};
#pragma pack(pop)

static_assert(sizeof(TransmissionGear) == 0xC, "Incorrect struct size: TransmissionGear");