// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct TxdDef	// sizeof = 0xC
{
	DWORD dictionary;
	WORD ref_counter;
	WORD parent_index;
	DWORD hash;
};
#pragma pack(pop)

static_assert(sizeof(TxdDef) == 0xC, "Incorrect struct size: TxdDef");