// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "RwV3D.h"


#pragma pack(push, 1)
struct VehicleStruct__internal	// sizeof = 0x20
{
	RwV3D field_0;
	DWORD field_C;
	DWORD field_10;
	DWORD field_14;
	DWORD field_18;
	DWORD field_1C;
};
#pragma pack(pop)

static_assert(sizeof(VehicleStruct__internal) == 0x20, "Incorrect struct size: VehicleStruct__internal");