// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "CMatrix.h"


#pragma pack(push, 1)
struct XYZ	// sizeof = 0x54
{
	CMatrix field_0;
	DWORD ptr;
	DWORD pPrev;
	DWORD pNext;
};
#pragma pack(pop)

static_assert(sizeof(XYZ) == 0x54, "Incorrect struct size: XYZ");