// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>
#include "XYZ.h"


#pragma pack(push, 1)
struct XYZStore	// sizeof = 0x1FC
{
	XYZ _l1Head;
	XYZ _l1Tail;
	XYZ allocatedListHead;
	XYZ allocatedListTail;
	XYZ freeListHead;
	XYZ freeListTail;
	DWORD pool;
};
#pragma pack(pop)

static_assert(sizeof(XYZStore) == 0x1FC, "Incorrect struct size: XYZStore");