// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>

#pragma pack(push, 1)
struct CStreamingInfo	// sizeof = 0x14
{
    unsigned short next;
    unsigned short prev;
    unsigned short nextOnCd;
    unsigned char  flags;
    unsigned char  img_id;
    unsigned int   offset;
    unsigned int   blocks;
    unsigned char  load_status;
    unsigned char  _pad[3];
};
#pragma pack(pop)

static_assert(sizeof(CStreamingInfo) == 0x14, "Incorrect struct size: SImgGTAItemInfo");
