// Copyright (C) 2013, Ennio Barbaro,
// Copyright (C) 2014, Pawel Tomulik.
//
// Use, modification, and distribution is subject to the Boost Software
// License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// See http://sbabbi.github.io/tinympl for documentation.
//
// You are welcome to contact the authors at:
//  enniobarbaro@gmail.com, ptomulik@meil.pw.edu.pl
//
#ifndef TINYMPL_TEST_CONFIG_HPP
#define TINYMPL_TEST_CONFIG_HPP

#define TINYMPL_ACCUMULATE_TEST_ENABLE 1
#define TINYMPL_ALGORITHM_TEST_ENABLE 1
#define TINYMPL_ALGORITHM_VARIADIC_TEST_ENABLE 1
#define TINYMPL_ALL_OF_TEST_ENABLE 1
#define TINYMPL_AND_B_TEST_ENABLE 1
#define TINYMPL_ANY_OF_TEST_ENABLE 1
#define TINYMPL_APPLY_TEST_ENABLE 1
#define TINYMPL_AS_SEQUENCE_TEST_ENABLE 1
#define TINYMPL_AT_TEST_ENABLE 1
#define TINYMPL_BIND_TEST_ENABLE 1
#define TINYMPL_BOOL_TEST_ENABLE 1
#define TINYMPL_CHAR_TEST_ENABLE 1
#define TINYMPL_COPY_IF_TEST_ENABLE 1
#define TINYMPL_COPY_N_TEST_ENABLE 1
#define TINYMPL_COPY_TEST_ENABLE 1
#define TINYMPL_COUNT_IF_TEST_ENABLE 1
#define TINYMPL_COUNT_TEST_ENABLE 1
#define TINYMPL_DIVIDES_TEST_ENABLE 1
#define TINYMPL_EQUAL_TO_TEST_ENABLE 1
#define TINYMPL_ERASE_TEST_ENABLE 1
#define TINYMPL_FILL_N_TEST_ENABLE 1
#define TINYMPL_FIND_IF_TEST_ENABLE 1
#define TINYMPL_FIND_TEST_ENABLE 1
#define TINYMPL_FUNCTIONAL_TEST_ENABLE 1
#define TINYMPL_FUSED_MAP_TEST_ENABLE 1
#define TINYMPL_FUSED_VALUE_MAP_TEST_ENABLE 1
#define TINYMPL_GENERATE_N_TEST_ENABLE 1
#define TINYMPL_GREATER_EQUAL_TEST_ENABLE 1
#define TINYMPL_GREATER_TEST_ENABLE 1
#define TINYMPL_IDENTITY_TEST_ENABLE 1
#define TINYMPL_IF_TEST_ENABLE 1
#define TINYMPL_INHERIT_TEST_ENABLE 1
#define TINYMPL_INSERT_TEST_ENABLE 1
#define TINYMPL_INT_TEST_ENABLE 1
#define TINYMPL_IS_SEQUENCE_TEST_ENABLE 1
#define TINYMPL_IS_UNIQUE_TEST_ENABLE 1
#define TINYMPL_JOIN_TEST_ENABLE 1
#define TINYMPL_LAMBDA_TEST_ENABLE 1
#define TINYMPL_LEFT_FOLD_TEST_ENABLE 1
#define TINYMPL_LESS_EQUAL_TEST_ENABLE 1
#define TINYMPL_LESS_TEST_ENABLE 1
#define TINYMPL_LEXICOGRAPHICAL_COMPARE_TEST_ENABLE 1
#define TINYMPL_LOGICAL_AND_TEST_ENABLE 1
#define TINYMPL_LOGICAL_NOT_TEST_ENABLE 1
#define TINYMPL_LOGICAL_OR_TEST_ENABLE 1
#define TINYMPL_LONG_TEST_ENABLE 1
#define TINYMPL_MAP_TEST_ENABLE 1
#define TINYMPL_MAX_ELEMENT_TEST_ENABLE 1
#define TINYMPL_MINUS_TEST_ENABLE 1
#define TINYMPL_MIN_ELEMENT_TEST_ENABLE 1
#define TINYMPL_MODULUS_TEST_ENABLE 1
#define TINYMPL_MULTIPLIES_TEST_ENABLE 1
#define TINYMPL_NEGATE_TEST_ENABLE 1
#define TINYMPL_NONE_OF_TEST_ENABLE 1
#define TINYMPL_NOT_B_TEST_ENABLE 1
#define TINYMPL_NOT_EQUAL_TO_TEST_ENABLE 1
#define TINYMPL_OR_B_TEST_ENABLE 1
#define TINYMPL_PLUS_TEST_ENABLE 1
#define TINYMPL_RATIO_TEST_ENABLE 1
#define TINYMPL_REMOVE_IF_TEST_ENABLE 1
#define TINYMPL_REMOVE_TEST_ENABLE 1
#define TINYMPL_REPLACE_IF_TEST_ENABLE 1
#define TINYMPL_REPLACE_TEST_ENABLE 1
#define TINYMPL_REVERSE_TEST_ENABLE 1
#define TINYMPL_RIGHT_FOLD_TEST_ENABLE 1
#define TINYMPL_SEQUENCE_TEST_ENABLE 1
#define TINYMPL_SET_DIFFERENCE_TEST_ENABLE 1
#define TINYMPL_SET_INTERSECTION_TEST_ENABLE 1
#define TINYMPL_SET_UNION_TEST_ENABLE 1
#define TINYMPL_SHORT_TEST_ENABLE 1
#define TINYMPL_SIZEOF_TEST_ENABLE 1
#define TINYMPL_SIZE_TEST_ENABLE 1
#define TINYMPL_SORT_TEST_ENABLE 1
#define TINYMPL_STRING_MACRO_TEST_ENABLE 1
#define TINYMPL_STRING_TEST_ENABLE 1
#define TINYMPL_TO_STRING_TEST_ENABLE 1
#define TINYMPL_TRANSFORM2_TEST_ENABLE 1
#define TINYMPL_TRANSFORM_MANY_TEST_ENABLE 1
#define TINYMPL_TRANSFORM_TEST_ENABLE 1
#define TINYMPL_TRANSPOSE_TEST_ENABLE 1
#define TINYMPL_UNIQUE_TEST_ENABLE 1
#define TINYMPL_UNORDERED_EQUAL_TEST_ENABLE 1
#define TINYMPL_VALUE_MAP_TEST_ENABLE 1
#define TINYMPL_VARIADIC_ACCUMULATE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_ALL_OF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_ANY_OF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_AT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_COPY_IF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_COPY_N_TEST_ENABLE 1
#define TINYMPL_VARIADIC_COPY_TEST_ENABLE 1
#define TINYMPL_VARIADIC_COUNT_IF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_COUNT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_ERASE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_FILL_N_TEST_ENABLE 1
#define TINYMPL_VARIADIC_FIND_IF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_FIND_TEST_ENABLE 1
#define TINYMPL_VARIADIC_GENERATE_N_TEST_ENABLE 1
#define TINYMPL_VARIADIC_INSERT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_IS_UNIQUE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_LEFT_FOLD_TEST_ENABLE 1
#define TINYMPL_VARIADIC_MAX_ELEMENT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_MIN_ELEMENT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_NONE_OF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_REMOVE_IF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_REMOVE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_REPLACE_IF_TEST_ENABLE 1
#define TINYMPL_VARIADIC_REPLACE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_REVERSE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_RIGHT_FOLD_TEST_ENABLE 1
#define TINYMPL_VARIADIC_SIZE_TEST_ENABLE 1
#define TINYMPL_VARIADIC_SORT_TEST_ENABLE 1
#define TINYMPL_VARIADIC_TEST_ENABLE 1
#define TINYMPL_VARIADIC_TEST_ENABLE 1
#define TINYMPL_VARIADIC_TRANSFORM_TEST_ENABLE 1
#define TINYMPL_VARIADIC_UNIQUE_TEST_ENABLE 1
#define TINYMPL_VECTOR_TEST_ENABLE 1
#define TINYMPL_ZIP_TEST_ENABLE 1

#endif // TINYMPL_TEST_CONFIG_HPP

